### ISSUE TITLE
User name can contain spaces

### ISSUE THREAD

**Issue by tanyagray** [neocities/neocities#1]
On the account settings page (and during sign up process) site/username description says "cannot contain spaces" but the name can successfully be changed to one with spaces.

Visiting the URL of a site with spaces in the name url-encodes the spaces, doesn't give a 404 or other error, and never loads.

**Comment by kyledrake** [comment]
Thank you for the report. I have tried to change a test account to have a space in it, and it did not let me do this. So I believe this has been fixed.

If it hasn't, please let me know and I will take a look. Thanks for the report! (And apologies for the delay in getting back to you).
