### ISSUE TITLE
Build ruby library interface to Let's Encrypt's ACME protocol

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#100]
When they launch this summer, we will be able to issue domain SSL certificates to sites on Neocities for free.

https://github.com/letsencrypt/boulder
https://github.com/letsencrypt/node-acme

If I understand this correctly, I believe I simply need to implement node-acme in ruby, because boulder is the reference implementation of what the Let's Encrypt project will eventually be providing.

**Comment by kyledrake** [comment]
https://github.com/letsencrypt/acme-spec

**Comment by nomadium** [comment]
I have not thoroughly reviewed it yet but it looks useful. https://github.com/unixcharles/acme-client

**Comment by kyledrake** [comment]
OH THANK FUCKING GOD. I did NOT want to write this. THANK YOU SO MUCH SERIOUSLY!

**Comment by kyledrake** [comment]
I don't know what it is, but I was having a *lot* of trouble figuring out the ACME spec.

**Comment by nomadium** [comment]
I had the same reaction, I tried to figure out the ACME spec in order to write a Ruby client library but I had trouble as well. I'm glad to see that after my vacations somebody took care of that.

**Comment by rugk** [comment]
FYI there are thousands of ACME/LE clients [available](https://letsencrypt.org/docs/client-options/), so you can choose nearly everything.

How is the [integration](https://letsencrypt.org/docs/integration-guide/) going on? As I see you currently still use a wildcard cert.

**Comment by rugk** [comment]
Ah so I see you use a wildcard cert for your own subdomain and LE certs for custom domains. This is fine if you want to pay for the wildcard cert. Otherwise you could also switch there to an LE cert.

**Comment by kyledrake** [comment]
We integrated this a while ago, closing.
