### ISSUE TITLE
Design alternative to mobile hamburger menu

### ISSUE THREAD

**Issue by violasong** [neocities/neocities#108]
We have few enough navigational links now that it would be straightforward to design a mobile view with all the links showing. More info: https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/

**Comment by kyledrake** [comment]
![](https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQwSnuhloE8_8YmXR0HCjMshhO_wMDfv8e-DtrlYNujbD0UaX3l4A)
