### ISSUE TITLE
Improve front page demo

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#111]
Right now it's just a picture of a hot dish recipe in an editor. We really need a full tour of all of the things on the site.

**Comment by kyledrake** [comment]
Browse button on bottom of previews
Make featured sites dynamic (kyle)

Images and descriptions of features and social activity on the site

**Comment by violasong** [comment]
Need a blurb about education

**Comment by violasong** [comment]
May do some more style adjustments, but this is basically done.
