### ISSUE TITLE
Begin the migration to default HTTPS for all sites

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#112]
The internet is going all-encryption, and we're no exception. We need to be HTTPS by default for sites. Google is going to start docking pages for not having it. There's no debate, we need to switch over.

Switching over means that third-parties can no longer observe what Neocities visitors are viewing on the site. NSA bullshit aside, this kind of third-party sniffing can be dangerous in more oppressive places on earth using deep packet inspection to do things like find dissidents.

This is going to cause a migration issue. Any sites that link to external resources that are not HTTPS will be considered "mixed content" and be blocked by all modern browsers. This is almost certainly going to break a lot of sites. It's worth the pain it's going to cause.

https://developer.mozilla.org/en-US/docs/Security/MixedContent/How_to_fix_website_with_mixed_content

We need to build a migration plan, that will likely require email notifications, a schedule for switching over, and some notifiers in our editing tool to warn users when they try to embed remote HTTP content.

**Comment by joppiesaus** [comment]
I wanted to open a issue about this, until I saw this. I think this will get more and more important over time. For example, [Chrome is slowly moving towards marking all HTTP webpages insecure](https://blog.chromium.org/2016/09/moving-towards-more-secure-web.html).

I've created a [Chrome extension](https://chrome.google.com/webstore/detail/neocities-https-forcer/jjfpdadedehehbckdimagdpbkieoopmn) that redirects everything on Neocities pages to HTTPS, but I don't think this is a solution, and I have experienced broken pages, most breaking pages had scripts over HTTP.

I think the main problem is that people don't really know about HTTPS and then they include a nice cursor from `http://www.cursors-4u.com` and then unintentionally create `mixed content` and break it all - especially if they're using scripts.

Idea: Create a `Content-Security-Policy` header with an `report-uri` that reports all these incidents, and then somehow notify the user about this and ask them to fix it. However I think developing this would require a lot of time.

Also, HTTPS is also useful for things like HTTP/2, creating a faster Neocities... Speaking of which is already present at Neocities. Just like HTTPS for _free_ sites! Amazing! Thank you for making Neocities awesome!

So, is this something to work on?

**Comment by kyledrake** [comment]
Yeah, this is a problem I'm not sure how well we're going to be able to solve this without breaking stuff unfortunately.

Content-Security-Policy: upgrade-insecure-requests is going to allow us to get closer - it will automatically try an https before breaking on mixed content, but support is not 100% with browsers yet.

I've been waiting for better CSP support adoption, notably IE and Safari are lagging behind. Once Safari gets CSP pushed to most users, I'm comfortable saying "hell with it" and migrating over.

report-uri hook is not a terrible idea, but as you said, it's going to be a lot of work probably.

This is something we're going to have to do eventually though. No question about that.

**Comment by kyledrake** [comment]
Done a while ago!
