### ISSUE TITLE
Draw over 9000 penelopes

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#113]
* Oscar award-winning Penelope
* Toy Penelope
* Guy Fawkes Penelope
* Hipster Penelope (hipster glasses and mustache)

**Comment by violasong** [comment]
- Brogrammer Penelope

**Comment by kyledrake** [comment]
DBZ Penelope (over 9000 views?)

**Comment by kyledrake** [comment]
Student Penelope (w/a education hat on)

**Comment by kyledrake** [comment]
@textfiles penelope (for talking about internet archive)

**Comment by violasong** [comment]
Didn't end up doing this but talk still went well
