### ISSUE TITLE
Per-site analytics

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#146]
Finish developing the infrastructure to do per-site statistics and analytics.

Right now we only track total views and hits for each site. It only provides an all-time amount of hits, which doesn't give us control to track growth in a good way. It also doesn't give us enough data to provide site metrics to our users.

We're using Webalizer as a base reference because it's still the best stats tool I've ever seen: http://www.webalizer.org/sample/usage_199905.html. Kindof amazing how much better a really old perl script is than most analytics tools out there (INCLUDING CLOUD SERVICES).

We need to track the following metrics to an accuracy of one day:
- Total hits
- Total views
- Total bandwidth served (we may need to cache a monthly version of this for administration)
- Referral URLs
- Browser types
- Where users are coming from (to an accuracy of city). **IP addresses will only be tracked for less than a day to calculate views and then thrown away** (this is the current behavior).

Upon implementation, we will start collecting these stats. @violasong will be designing a stats page for individual sites.

Going forward, we will implement hooks to let users know when they hit certain milestones (first in a country, first 1000 views, etc), related to #50.

This is not related to #145, which will be expanded for stats and analytics of neocities.org itself (the main site).

**Comment by rugk** [comment]
What about [Piwik](https://piwik.org/)?

**Comment by rugk** [comment]
And BTW if you also track it on user pages, please allow the users to shut it off. (not everyone wants to track their users)

**Comment by Jacklack3** [comment]
"high-priority"
uuuuhhhhh

**Comment by kyledrake** [comment]
Was finished years ago sans gamification stuff, so I'll just close it.
