### ISSUE TITLE
Design site stats page

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#147]
See #146.

**Comment by violasong** [comment]
RE: Last 7 Days chart — As far as adding "hits" and "views" to the legend popup that appears on hover, this is the example option that they say to add to the call. I couldn't get it to work however:
```
legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].strokeColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>"
```
http://www.chartjs.org/docs/#line-chart-chart-options
