### ISSUE TITLE
Save shortcut for Mac

### ISSUE THREAD

**Issue by itsgreggreg** [neocities/neocities#148]
Use Command+s instead of control+s to save files in the editor on a Mac.

**Comment by kyledrake** [comment]
@itsgreggreg  Could you type command+s into this thinger and tell me what it says in the box? http://robertwhurst.github.io/KeyboardJS/

**Comment by itsgreggreg** [comment]
Unfortunately that site doesn't capture the command key either and so pressing command+s results in the firefox save file dialog box opening and only the 's' key showing in the demo area.

On this site, http://unixpapa.com/js/testkey.html , i get:
keydown  keyCode=224       which=224       charCode=0        
keydown  keyCode=83  (S)   which=83  (S)   charCode=0        
keypress keyCode=0         which=115 (s)   charCode=115 (s)  
keyup    keyCode=224       which=224       charCode=0   

And this SO question indicates that the code is browser specific:
http://stackoverflow.com/questions/3902635/how-does-one-capture-a-macs-command-key-via-javascript#3922353

**Comment by itsgreggreg** [comment]
Just tested it in safari and it seems to work with this result:
command, windows, win, super, leftcommand, leftwindows, leftwin, leftsuper, s

but it only works with the left command key and not the right.

Looking at the source they have the keycodes hard coded as 91 and 92 which will only work in safari/chrome for left command and 92 should be 93 at least on mac.
https://github.com/RobertWHurst/KeyboardJS/blob/master/keyboard.js

**Comment by itsgreggreg** [comment]
I went ahead and forked the library and added it: https://github.com/itsgreggreg/KeyboardJS/commit/cbb3a62195dbc73c59f38f78c061db2cb801151b

You can test it here: http://itsgreggreg.github.io/KeyboardJS/

**Comment by kyledrake** [comment]
Thank you for looking into this and issuing a fix!

I will deploy your version right now.

**Comment by kyledrake** [comment]
https://github.com/RobertWHurst/KeyboardJS/pull/83

**Comment by kyledrake** [comment]
Actually I'm going to wait for the results of the PR before deploying, hopefully they pull it and do a release, easier for us. Keep me in the loop!
