### ISSUE TITLE
SFTP/GIT upload support

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#149]
Not a strong priority for now, but adding some tidbits here I probably need to attempt this:
http://serverfault.com/questions/117857/is-it-possible-to-use-custom-script-for-authentication-with-pam
http://www.jstorimer.com/blogs/workingwithcode/7766107-a-unix-shell-in-ruby

**Comment by kyledrake** [comment]
https://github.com/gitlabhq/gitlab-shell

**Comment by kyledrake** [comment]
http://stackoverflow.com/questions/402615/how-to-restrict-ssh-users-to-a-predefined-set-of-commands-after-login

**Comment by kyledrake** [comment]
https://github.com/wconrad/ftpd

**Comment by rugk** [comment]
I would prioritize git over ftp. I mean if you see how famous and often-used GitHub pages is, you can see the potential there.

**Comment by emsenn** [comment]
I came to this issue because I missed this page on the main website: https://neocities.org/cli

You could probably close this since the neocities CLI allows for CI/CD.

**Comment by kyledrake** [comment]
Agreed.
