### ISSUE TITLE
Additional pricing tiers

### ISSUE THREAD

**Issue by violasong** [neocities/neocities#15]
While the current $5 plan seems like a good basic option for upgrading one's Neocities space while supporting the site, we should add some higher-priced tiers. I'm sort of intending these for tech community members who don't necessarily need hosting but want to sponsor the idea of free hosting for everybody else.

Tier ideas:
- $25/month - Everything in supporter, plus t-shirt (may not be practical to offer for international users)
- $100/month - Everything in $25 tier, plus (optionally) name or company name on homepage

Considerations:
- We could say they'll ship in 4-6 weeks to help with t-shirt cost flow, give us a better idea of demand, and remove t-shirt doneness as a dependency for announcing these tiers
- Sign up process needs to be updated to take shipping address, t-shirt size, maybe a checkbox for those who want to opt out of receiving physical items
- Victoria needs to do final tweaks on vector logo to prepare for vendor
- Could repurpose Cat Bus and Fat Cat names/graphics for these tiers
- If we can decide on t-shirt color, Victoria can make a little t-shirt graphic to put in the page. The plans section should probably be redesigned... maybe to reflect that these are donation tiers, not hosting plans... well, this will require some thought from me. Support page should communicate, "Help us bring free hosting to everyone! (and get cool nerdy shirt in the process)"
- T-shirt color decision probably depends on vendor decision. Kyle had a vendor in mind (which I've lost track of), but if we want this to be really easy we may want to look into a company that will not only print, but also pack/ship the shirts for us. Mac companies like BuyOlympia. (I've talked to them in the past - their minimum was 72 shirts, which would include women's sizes. I could get a quote)
- Ideally a sticker would be offered with all plans. Mac companies like stickermule which does awesome velvety die-cut stickers. This complicates order fulfillment though. Is there a vendor that is awesome with both shirts and stickers? EDIT: Actually, I think stickers complicate things too much. Maybe we hand them out at conferences later, or maybe I just get one made for myself lol
- For people who don't like subscriptions, I feel we could offer the t-shirt with one-time $100 donations as well
- Get testimonials from educators, etc so we can better explain the benefits of the project
- Should really have a section on the homepage for this... but different from what we had planned before. Less about pricing plans and more about why to support us.

**Comment by kyledrake** [comment]
I like the new tiers. We should do this.

I wonder if the $100/mo should be even higher - like $400/mo or something.

I think we should have a supporters page which lists all the current supporters in a single place.

**Comment by violasong** [comment]
Re: $400 - I'm not sure. For $100 I was thinking of small indie companies whose founders would be checking out Neocities on their own; when it comes to larger companies we would probably want to contact them directly and request more, and perhaps offer small logo placement instead of just name in text. Might not want to open logo sponsorship to just any company since it seems to indicate a stronger association.

**Comment by violasong** [comment]
We basically did the kickstarter instead of this
