### ISSUE TITLE
Create a White Hat program

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#152]
Give free supporter accounts to people that discover legitimate security problems with Neocities.

**Comment by rugk** [comment]
A current famous platform is https://hackerone.com/. Even GitHub uses it now.

**Comment by tyuo** [comment]
Good thing to be added along with acnowledgement.
"Give free supporter accounts to people that discover legitimate security problems with Neocities."

**Comment by kyledrake** [comment]
I ran one on hackerone for a while, it did alright but there was a lot of overhead (people reporting dumb fake things like "I can upload html!". I might turn it back on again in the future...
