### ISSUE TITLE
Recursive directory drag-n-drop

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#157]
It's kindof possible, I think:

http://stackoverflow.com/questions/5826286/how-do-i-use-google-chrome-11s-upload-folder-feature-in-my-own-code/5849341#5849341

http://stackoverflow.com/questions/3590058/does-html5-allow-drag-drop-upload-of-folders-or-a-folder-tree

**Comment by stunklegran** [comment]
I'd frickin' love to see this happen. It would be so much easier to manage files in Neocities that way. I would totally love to help... except I know virtually nothing about higher-end web development.

**Comment by kyledrake** [comment]
Okay, so it's implemented, I think: https://github.com/neocities/neocities/commit/f00e5d0757b6cdb04d1d74b2bba7029b67e5f3a9

THIS ONLY WORKS ON CHROME. Apparently the W3C standard proposal was "abandoned" and all the other browsers refuse to implement it. It's their loss, as this is a big deal. Use Chrome if you need to do this. :)
