### ISSUE TITLE
neocities and lxc.

### ISSUE THREAD

**Issue by xcasex** [neocities/neocities#162]
i've made some cursory changes to the vagrant provisioning to enable use of lxc. 
but, there's an issue with getting the webapp to run inside the container.

'agrant@vagrant-base-trusty-amd64:/vagrant$ bundle exec rackup
/vagrant/environment.rb:29:in `<top (required)>': undefined method `[]' for nil:NilClass (NoMethodError)
	from /vagrant/app.rb:1:in `require'
	from /vagrant/app.rb:1:in `<top (required)>'
	from /vagrant/config.ru:2:in `require'
	from /vagrant/config.ru:2:in `block in <main>'
	from /var/lib/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
	from /var/lib/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
	from /vagrant/config.ru:in `new'
	from /vagrant/config.ru:in `<main>'
	from /var/lib/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
	from /var/lib/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
	from /var/lib/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
	from /var/lib/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
	from /var/lib/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
	from /var/lib/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
	from /var/lib/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:250:in `start'
	from /var/lib/gems/2.2.0/gems/rack-1.5.2/lib/rack/server.rb:141:in `start'
	from /var/lib/gems/2.2.0/gems/rack-1.5.2/bin/rackup:4:in `<top (required)>'
	from /usr/local/bin/rackup:23:in `load'
	from /usr/local/bin/rackup:23:in `<main>''

**Comment by kyledrake** [comment]
Looks like you're missing the config.yml file. You need to copy config.yml.template and configure it appropriately.

**Comment by xcasex** [comment]
but that defeats the point of using vagrant?

**Comment by kyledrake** [comment]
How are you using Vagrant to push to LXC? Is there a blog post that talks about this? We might be interested in using it. :)

**Comment by xcasex** [comment]
Oh I could do a writeup :)

**Comment by xcasex** [comment]
Vagrant and LXC basically comes down to:
$ vagrant plugin install vagrant-lxc
$ vagrant plugin install lxc

and modifying the vagrant file thus:

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'fgrehm/trusty64-lxc'
  config.vm.provision :shell, path: './vagrant/development.sh'
  config.vm.network :forwarded_port, guest: 9292, host: 9134

  config.vm.provider :lxc do |lxc|
  end
end

**Comment by kyledrake** [comment]
As I understand it, vagrant should provide all the files in the directory as a /vagrant, and those files are accessible from the machine. You should be able to provide a config.yml for it, I believe.

The config.yml is required to start the application. It -should- work in a vagrant box with the default values (it does for me anyway). I think it just gets it from the /vagrant directory.

Sorry if this isn't helpful - I've never tried to use vagrant with lxc. But the missing config.yml is definitely the cause of this exception.
