### ISSUE TITLE
Dashboard file list view

### ISSUE THREAD

**Issue by violasong** [neocities/neocities#166]
Add a way to view files as a list/table instead of icons. (While I'm at it, make something that works on mobile.

Eventually #134 Textmate-like editor might replace this, but it'll be useful for now.

**Comment by violasong** [comment]
Kyle needs to hook up the icons that will switch between the views (there's a CSS class that can be swapped out). 

Also, file list view is what mobile users should see.

**Comment by kyledrake** [comment]
dashboard_list branch
