### ISSUE TITLE
https://www.neocities.org/ gives a 404

### ISSUE THREAD

**Issue by book** [neocities/neocities#171]
The link at the top of <https://github.com/neocities/> is https://www.neocities.org/ and should be <http://neocities.org/>.

Unless you expect some user to register the name `www`, you should probaly make <http://www.neocities.org/> a 301 to <http://neocities.org/>.

**Comment by kyledrake** [comment]
The problem was that the redirect was on our WWW proxy, not the proxy for the sites. This was indeed a mistake.

I've fixed this by adding a www.neocities.org that points to our front site. Thank you for the report!
