### ISSUE TITLE
Implement Honeypot API

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#175]
http://www.projecthoneypot.org/services_overview.php

**Comment by rugk** [comment]
Better https://www.projecthoneypot.org/maintenance/maintenance.html 😉 (although their TLS config is not optimal)

**Comment by rugk** [comment]
Is it implemented or why do you close this issue?

**Comment by kyledrake** [comment]
It's been in maintenance mode for months. I'm not going to implement it if it's a dead project. I more left this as a note incase I decided I wanted to, but now I definitely won't.
