### ISSUE TITLE
Text search box position

### ISSUE THREAD

**Issue by fionnachan** [neocities/neocities#183]
![search text](https://cloud.githubusercontent.com/assets/13184582/8844588/4d9ec7b8-3149-11e5-9ca4-b18f59e68494.png)
This box is not fixed to the screen, it disappears when we scroll down.
It is not urgent at all. I just thought to bring it up.

**Comment by brandly** [comment]
Looks like you want

```css
.ace_search {
    position: fixed;
    top: 105px;
}
```

However, when the screen is more narrow and the header links collapse into a hamburger button, the header loses a vertical pixel somewhere, and it'll be `top: 104px;`. At least that's what I'm seeing on Chrome 44

**Comment by kyledrake** [comment]
This took _way_ too long to get to, but I've implemented your proposed fix. Thanks for the report!

**Comment by brandly** [comment]
thanks kyle!!
