### ISSUE TITLE
Links broken on https://neocities.org/blog

### ISSUE THREAD

**Issue by reidab** [neocities/neocities#185]
Accessing the blog via https://neocities.org/blog (linked in the footer) looks like it fetches and re-serves the content of http://blog.neocities.org. Since all the links on http://blog.neocities.org are root-relative and include a .html suffix (e.g. `/neocities-reaches-10k-kickstarter.html`), they wind up linking to pages like https://neocities.org/neocities-reaches-10k-kickstarter.html, which 404s, instead of https://neocities.org/blog/neocities-reaches-10k-kickstarter, which works.

**Comment by violasong** [comment]
Hi Reid! Thanks for pointing this out, am fixing it now.

**Comment by kyledrake** [comment]
Okay, so I just changed the code to redirect https://neocities.org/blog to https://blog.neocities.org

When I launched I had this idea of not having official stuff on the subdomains, but I'm just going to use blog.neocities.org as the canonical to solve the weirdness associated with this.

**Comment by kyledrake** [comment]
Thanks Reid!
