### ISSUE TITLE
editor interface hangs on big pastes

### ISSUE THREAD

**Issue by substack** [neocities/neocities#187]
Pasting html code with inline browserify bundles can be very, very slow and the interface locks up trying to syntax highlight everything.

**Comment by kyledrake** [comment]
Could you give me a url for the file? I might be able to make it not try to do that if it's minimized, I feel like there's a way to detect this.

You could also use the API to upload. I actually made the API at the old sudo room so you didn't need to use the browser editor IIRC :)

**Comment by substack** [comment]
I've been using the upload button more now, but it's handy to paste from the clipboard.

Here's a representative URL that is super slow in the editor: http://substack.neocities.org/aim.html

**Comment by substack** [comment]
Here's a pretty slow example: https://substack.neocities.org/virtual_dom_unidirectional.html

**Comment by kyledrake** [comment]
Not much I can do here unfortunately, except to maybe update to the latest ace editor (which I will do in the near future). I guess the syntax highlighter has issues with compiled js...
