### ISSUE TITLE
surfinject.js sometimes getting tacked on after closing html tag

### ISSUE THREAD

**Issue by ahuanguchi** [neocities/neocities#188]
After I leave my index.html page untouched for a few days, my home page starts getting served with `<script src="https://neocities.org/js/surfinject.js"></script>` after the `</html>` tag. This calls `setAttribute('target', '_blank')` on all of the links on the page, which is sort of inconvenient. However, this problem temporarily goes away whenever I update index.html. Also, it doesn't seem like it's happening to everyone. Is this just a weird server issue?

Edit: This happens when you visit d-m-adventure.neocities.org, not just when you're in surf mode.

**Comment by kyledrake** [comment]
Thank you for reporting this, this is a bug with our new CDN. We have geo-cached sites now, but I need to have it take into account the arguments. I will get to work on this ASAP.

The surf inject is only supposed to be there for the /browse surf viewing to get around restrictions with iframes. What it's doing is caching it with the embedded script and then serving it for the normal stuff. Definitely not OK.

**Comment by kyledrake** [comment]
Okay, I just turned off the surfinject code for now, and flushed all the caches, so it should be okay now. This will make the surf mode not work well for now, but I won't re-enable it until we can figure this out.

My apologies for this issue.
