### ISSUE TITLE
Sites remain live after deletion

### ISSUE THREAD

**Issue by falloney** [neocities/neocities#191]
All versions of site live more than one week after site deletion

**Comment by kyledrake** [comment]
We had a 15 day cache that was not being purged when files were deleted. I've set the timer to 30 minutes for now, and am working on a solution for near-time deleting.

**Comment by falloney** [comment]
When will the sites be erased if the files weren't deleted?

**Comment by kyledrake** [comment]
They should be gone. If not, please send me the site URL that is still there and I will look into it.

**Comment by falloney** [comment]
They are still there: sugarbullet.neocities.org (only the front page
deleted) and milagro.neocities.org

**Comment by falloney** [comment]
I sent the links. Will you be able to delete them?

**Comment by falloney** [comment]
thanks so much for removing them!
