### ISSUE TITLE
Neocities front page incorrectly shows mobile mode for some browsers

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#192]
User Agent:

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

/cc @whyrusleeping

**Comment by kyledrake** [comment]
![xswx8tm](https://cloud.githubusercontent.com/assets/28153/9591155/66e4b98a-4fee-11e5-9630-2546ac73ffba.png)

**Comment by whyrusleeping** [comment]
If it helps any, i have a retina screen, and run chrome with `chromium --force-device-scale-factor=1.4`

**Comment by kyledrake** [comment]
I started it with `chromium-browser --force-device-scale-factor=1.4` and it still loads fine. Could you try reducing the zoom on the page and see if that fixes it?

The site is responsive, so it should just drop down to the regular size when it detects enough real estate in the window.

**Comment by kyledrake** [comment]
Couldn't reproduce, closing.
