### ISSUE TITLE
Site preview not rendering correctly

### ISSUE THREAD

**Issue by geek1011** [neocities/neocities#194]
![Site Preview](https://cloud.githubusercontent.com/assets/13909717/10715750/0c64817c-7af8-11e5-8ebc-2c527fdd99d9.PNG)

The site preview of [my site](http://neocities.org/site/pgpg4822) is not rendering properly in Neocities. It renders properly in every other site snapshot tool I have tried. This is also happening with a few other sites I have seen on Neocities.

**Comment by kyledrake** [comment]
PhantomJS doesn't like rendering your page, and I don't know why.

test.js:
```
var page = require('webpage').create()

page.open('http://pgpg4822.neocities.org', function() {
  page.viewportSize = { width: 1280, height: 960 }
  page.clipRect = { top: 0, left: 0, width: 1280, height: 960}
  page.render('test.png')
  phantom.exit()
})
```

Running `phantomjs test.js` produces:

![github](https://cloud.githubusercontent.com/assets/28153/11139574/2fa1e1d8-8986-11e5-9e46-c6fed5de9bce.png)

Which is better, but still not there. I'm not sure how to fix this. You're welcome to play with PhantomJS options to try to find a solution here: 

http://phantomjs.org/screen-capture.html

**Comment by Chocolate-Chip-Computing** [comment]
Often times the little preview box does not render it correctly only due to size in the page, and the CSS designed to a certain monitor rather than neutral

**Comment by geek1011** [comment]
@Chocolate-Chip-Computing It is not that. I have tried testing it on many different devices, and removing some of my css.

**Comment by kyledrake** [comment]
I've been experimenting with a new JS script and PhantomJS 2.0, and I've been getting better results. I'm still working on it.

![better](https://cloud.githubusercontent.com/assets/28153/11168137/ee3303cc-8b37-11e5-83fc-b0b550dc1b5c.png)

**Comment by kyledrake** [comment]
Okay, the new code is deployed. It's definitely better, but it still renders some of your pages strangely (scripts.html for example). I'm going to keep tuning it to see if I can improve these sites as well.

**Comment by geek1011** [comment]
@kyledrake Good job. Thank you soo much!
