### ISSUE TITLE
Disable auto insertion of matching characters in ACE editor

### ISSUE THREAD

**Issue by jbaudanza** [neocities/neocities#197]
I recently volunteered with an organization called codeed.org to teach some basic HTML skills to some middle school students. Neocities is a great tool for this, but we found that autocomplete function gets in the way more than it helps. I can disable this functionality from the javascript console with the following snippit:

```javascript
var editor = ace.edit("editor");
editor.setBehavioursEnabled(false);
```

It would be great if there was an option in neocities to do this. Let me know what you think. I'd be happy to put together a PR.

**Comment by GeaRSiX** [comment]
I don't see why not - more options is always good. :+1:
Might be worth considering the possibility of future feature-creep when implementing functionality like this though, I think it's important for the editor to stay simple & streamlined for less experienced users.

**Comment by careytan** [comment]
I second this request! Autocompletion is a handy feature for experienced coders, but for the beginner it can be confusing. Almost every kid I've taught has been regularly tripped up by it, despite my best efforts to explain it to them. I'd really love to be able to toggle it on/off.

**Comment by kyledrake** [comment]
Should be G2G, thanks for the feedback.

**Comment by jbaudanza** [comment]
Thanks guys! We had another session today and this change was a big help for the kids.
