### ISSUE TITLE
Custom 404 not displaying

### ISSUE THREAD

**Issue by ghost** [neocities/neocities#199]
I have a custom 404 page. However, when attempting to view it directly, it goes to the default.

http://choco.neocities.org/not_found.html

and a fake directory to show the actual 404

http://choco.neocities.org/hghghghgksjfhenrofgr

**Comment by kyledrake** [comment]
Finally figured out how to fix this. Should be good now. Sorry for the delay - the nginx code behind this was very weird and complicated. It took a while figure out a fix.
