### ISSUE TITLE
Uploading an empty file is not possible

### ISSUE THREAD

**Issue by tanyagray** [neocities/neocities#2]
**Description:**
Uploading an empty file results in a "successful" upload, but the file is not actually uploaded.

**To reproduce:**
- Create an empty file "styles.css"
- Upload the file to the site

Has not been tested for other file types but was noted for empty css files.

**Use case:**
Uploading a "starter page" during our workshops includes a skeleton HTML page and a linked (empty) stylesheet. Uploading both files so that students can start coding directly in Neocities is not possible.

**Workaround:**
Add a comment at the top of the otherwise empty file before uploading.

**Comment by kyledrake** [comment]
This has been fixed with the newest version of Neocities! Thank you for the report.
