### ISSUE TITLE
Feature Request: Directory Listings

### ISSUE THREAD

**Issue by Chocolate-Chip-Computing** [neocities/neocities#200]
I am requesting the adding of a feature that allows the listing of files within a directory, rather than giving a 403 response.

**Comment by kyledrake** [comment]
I've pondered this more than a few times, and decided it wasn't a good idea to implement it.

One of the important philosophies I have for deciding Neocities features is that we should not implement anything that makes a site depend on the backend.

This decision has led to some unfortunate consequences (no APIs for sites, no directory listings), but in the long term, it improves site erosion resistance, and I think that's important enough to make the sacrifice. If I implement this and then the backend providing it changes, it would cause that link to break, and if a site was to depend on that, the site may stop working.

An additional problem is that there would be no way to style that interface with what we're using right now, it would be whatever the backend sets up as default. Changing this behavior would require some pretty crazy code that doesn't exist, and a few "tricky hacks" to figure out what CSS file to render from. I'd rather not go down that road for the "dependence" reason again.

Another big reason is that it encourages "file dumping". I want us to focus on being a place for web sites to be created.

Thank you for the suggestion, I do agree that a directory listing would be helpful.
