### ISSUE TITLE
Storage Size Error

### ISSUE THREAD

**Issue by Chocolate-Chip-Computing** [neocities/neocities#201]
Previously (and breifly) the dashboard would say the file size of each file. This feature has gone away for myself. Furthermore, the counter which says my entire website size only started counting at 5GB, so now I  have a site at least over 7GB, but it reports it as 1.28MB. I do not know what would happen when I reach the actual size, but I don't think it'd be good.

**Comment by kyledrake** [comment]
That's not good, I'll definitely investigate. What's your username?

**Comment by kyledrake** [comment]
You don't have several GB, but the counter in the DB is different than the amount of space you're using, which is obviously not good.

We're currently working on a new storage system that's going to resolve a lot of issues like this, and also provide more free space than we can right now. As it's implemented right now we've got two file databases: the filesystem and a copy of that data in the SQL database, and I have to run my own file system for the sites.

My long term goal is to get Neocities out of the file storage business - our goal is to provide web site creation. The thing stopping the migration is that the options available are not ideal ("cloud file" services have exorbitant costs and/or god-awful DDoS protections).

**Comment by kyledrake** [comment]
https://github.com/neocities/neocities/commit/b2bdcfd1f5f1fe57c77f08e66904e839c3360156 should fix this for now
