### ISSUE TITLE
Feature Request: IPFS Opt-Out

### ISSUE THREAD

**Issue by ghost** [neocities/neocities#202]
I know this is going to come up eventually, so it might as well be said now.Some people would like to have the ability to choose not to submit their websites to the IPFS distributed network. A downside to IPFS is that is designed to retain files forever.  some people do not want this, so I am providing this feature request as just a "Head's up!"

**Comment by phikal** [comment]
But anyone can download your page via HTTP and rehost it like the internet archive does. The chance of someone randomly fining it is minimal too. If IPFS is going to start and replace HTTP, it will be neocities the site where it all began.

**Comment by Chocolate-Chip-Computing** [comment]
While that is true, I can just imagine it being something that someone complains about. It should at least be designed to honor a robots.txt file, which it does not seem to be doing at the moment.

**Comment by rugk** [comment]
Huh, interesting. I did not know it does this, it should also be stated somewhere at least.

**Comment by kyledrake** [comment]
There is now a checkbox to disable ipfs archiving if you want to.

**Comment by rugk** [comment]
And where is it? Should not this button be on `https://neocities.org/site/<username>/archives` somehow?

**Comment by kyledrake** [comment]
Site settings.
