### ISSUE TITLE
Remove proprietary, user-tracking dependency on ReCaptcha

### ISSUE THREAD

**Issue by ghost** [neocities/neocities#207]
ReCatcha's JavaScript is proprietary software, and it allows Google to track people. I suggest it is replaced with a free alternative.

**Comment by kyledrake** [comment]
I would love to do this (it's our remaining external dep), but will need some very strong alternatives that are actually going to keep out spammers and bots.

**Comment by Chocolate-Chip-Computing** [comment]
On Fri, 2016-02-12 at 10:04 -0800, Kyle Drake wrote:
> I would love to do this (it's our remaining external dep), but will
> need some very strong alternatives that are actually going to keep
> out spammers and bots.
> 
There's a good one that 8chan made and uses. It's in PHP and it's
hosted server-side. Open Source too.

-- 
Signed,
The one, the only, Chocolate Chip!
chocolatechip@derpymail.org
*****************************************************************
* To all members of the National Security Administration, I say *
* this with full malice: Fuck you! I am not afraid to say that  * 
* in an email signature. Never be afraid.                       *
*****************************************************************

Read the PGP Header and check that it is me!
https://choco.neocities.org/pgp/

  ,= ,-_-. =.
 ((_/)o o(\_))
  `-'(. .)`-'
      \_/ Support the GNU/Life. https://gnu.org/philosophy

**Comment by Chocolate-Chip-Computing** [comment]
Sorry. I forgot to link it.

https://github.com/ctrlcctrlv/infinity/tree/master/8chan-captcha


-- 
Signed,
The one, the only, Chocolate Chip!
chocolatechip@derpymail.org
*****************************************************************
* To all members of the National Security Administration, I say *
* this with full malice: Fuck you! I am not afraid to say that  * 
* in an email signature. Never be afraid.                       *
*****************************************************************

Read the PGP Header and check that it is me!
https://choco.neocities.org/pgp/ 

  ,= ,-_-. =.
 ((_/)o o(\_))
  `-'(. .)`-'
      \_/ Support the GNU/Life. https://gnu.org/philosophy

**Comment by kyledrake** [comment]
Thanks for the idea. I agree long term that we would rather use our own. I will keep on the lookout for new ideas for running our own captcha, but for the moment we're going to keep recaptcha. We don't run PHP in our environment so implementing this particular captcha would be prohibitively difficult as well.
