### ISSUE TITLE
Ability to list site files via API

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#208]

**Comment by geek1011** [comment]
I would need it to return a plain text list of all files. It would include empty directories. An example would be:

````
$ curl https://USER:PASS@neocities.org/api/list
/index.html
/blankdir
/blog
/blog/index.html
/images
/images/image1.png
/images/image2.png
````

**Comment by geek1011** [comment]
After this support is added, I would add the Jekyll plugin within a few weeks.

**Comment by geek1011** [comment]
You could watch my GitHub repo: https://github.com/geek1011/NeocitiesTools

**Comment by kyledrake** [comment]
Thank you for clarifying. I'm going to try to get to this tonight.

**Comment by kyledrake** [comment]
Alright! https://github.com/neocities/neocities/commit/bbe57750da210c6175fb488aa153732ad61c6897
There's documentation at https://neocities.org/api

Let me know if you run into any issues. Thanks for the suggestion!

**Comment by geek1011** [comment]
Thanks!
