### ISSUE TITLE
Code examples overflow

### ISSUE THREAD

**Issue by plfstr** [neocities/neocities#209]
Seen on /api, the examples break out of their `<code>` element.

**Comment by kyledrake** [comment]
I'm not seeing this. Could you take a screenshot?

**Comment by plfstr** [comment]
Sorry I should have specified. It is at narrow viewport widths - the shorter cURL examples overflow

**Comment by kyledrake** [comment]
It doesn't overflow anymore, I must have fixed it at some point. Thanks!
