### ISSUE TITLE
Can't sign up/in with Safari (OS X)

### ISSUE THREAD

**Issue by famousgarkin** [neocities/neocities#217]
Safari just redirects back to default https://neocities.org with no errors or messages. Chrome works alright.

Safari 9.1 (11601.5.17.1)
OS X 10.11.4 (15E65)

**Comment by scottaohara** [comment]
that's strange.

i just signed up with no issues using:
safari 9.1
OSX 10.10.5

**Comment by rigconfig** [comment]
Same happend to me with Chrome, but I was able to login when I tried incognito mode. So I ...
- opened Chrome Dev Tools
- went to **Application** tab
- then hit `"Clear site data"` at the bottom.

Then it worked. So clear your cache and application caches, then try again.

**Comment by rognoni** [comment]
Similar error with **Tor Browser** 6.0.6

**Comment by kyledrake** [comment]
This was likely a bug related to recaptcha that has hopefully been fixed. Out of my control, nothing I can really do here, so I'm closing for now.
