### ISSUE TITLE
tags with caps in it don't go though search right

### ISSUE THREAD

**Issue by pokeball99** [neocities/neocities#218]
http://that1archive.neocities.org/
doesn't show up with [archive,](https://neocities.org/browse?sort_by=followers&tag=archive) [Archive](https://neocities.org/browse?sort_by=followers&tag=Archive) shows nothing, [fbi](https://neocities.org/browse?sort_by=followers&tag=fbi) and [FBI](https://neocities.org/browse?sort_by=followers&tag=FBI) does that same thing, not sure where exactly is causing this error

**Comment by pokeball99** [comment]
any update on this?

**Comment by kyledrake** [comment]
This was related to an earlier algorithm that detected "crashing sites", but the results were largely erroneous. I've removed the crashing sites designation for this site, and that should fix things. Thanks!
