### ISSUE TITLE
overly aggressive content-security-policy change broke pages

### ISSUE THREAD

**Issue by substack** [neocities/neocities#220]
A recent change seems to have added much more aggressive content security policy settings:

```
$ curl -I https://kitties.neocities.org
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 18 May 2016 19:44:29 GMT
Content-Type: text/html
Connection: keep-alive
Access-Control-Allow-Methods: GET, HEAD, OPTIONS
Access-Control-Allow-Origin: *
X-Cached: MISS
Content-Security-Policy: upgrade-insecure-requests; default-src 'unsafe-inline' 'unsafe-eval' 'self' *; frame-ancestors 'self' neocities.org
Upgrade-Insecure-Requests: 1
```

This breaks pages that use inline data URIs, for example:
- https://kitties.neocities.org/camra.html
- https://mafintosh.neocities.org/

It also means that pages using [webworkify](https://npmjs.com/package/webworkify) don't work on neocities anymore.

**Comment by kyledrake** [comment]
This went out with our new proxy network, with the idea of reducing certain kinds of phishing attacks (and the hope it wouldn't cause issue for legitimate sites).

I'm going to remove this right now, apologies about the issues!

**Comment by kyledrake** [comment]
OK, this is removed for now until I can figure out how to make it better.

Do you know how we could change that Content-Security-Policy to work with what you're doing? Is it the `unsafe-inline` that's the culprit here?

**Comment by substack** [comment]
Going through the [source list reference](http://content-security-policy.com/#source_list) for default-src, it seems that:
* `'unsafe-inline'` - allows onclick, script tag bodies
* `'unsafe-eval'` - allows `eval()`, `Function()`
* `'self'` - allows loading script tags from the same origin
* `*` - allows any URL except `data:` `blob:` `filesystem:` schemes.

So `data:` and `blob:` schemes are being left out. I see there is a record for `data:` that can be sent in the header, it seems like that will fix most of the issues. Pages that use `URL.createObjectURL()` might also need `object-src 'self' blob:` [according to here](http://stackoverflow.com/questions/28467789/content-security-policy-object-src-blob).

**Comment by kyledrake** [comment]
Just to provide an update on this, @substack's proposed change will go in with the transition to default SSL at the beginning of the 2017 year. We'll reopen this ticket if we run into any issues again. Thanks for looking at this!

**Comment by evhan55** [comment]
Hello!  I was linked here by someone in the AFrame slack when I showed them this error I got on my neocities page:

```
Refused to load the image 'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20xm…83%2C44.936%2C30.296%2C45.201%2C30.296z%22%3E%3C/path%3E%3C/g%3E%3C/svg%3E' because it violates the following Content Security Policy directive: "default-src 'unsafe-inline' 'unsafe-eval' 'self' blob: *". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
```

Seems the AFrame VR goggles icon is being rejected and instead renders a plain rectangle on the bottom right:

evhan55.neocities.org

I'd really love to use neocities to run AFrame workshops because it hosts files and assets so elegantly.  Any idea if the VR goggles icon can be allowed to load?

Thank you so much!

**Comment by joppiesaus** [comment]
Hmm. My crappy A-Frame thingy seems to work: https://joppiesaus.neocities.org/vr/space2.html
And this one too: https://liooil.space/VR_webStuff/room+07/room07.html

**Comment by evhan55** [comment]
Thank you for sharing, @joppiesaus !
I wonder if it's because you link to aframe hosted on neocities itself?

**Comment by joppiesaus** [comment]
I have no idea. [This](https://liooil.space/VR_webStuff/room+12/mobleTeleport.html) thing loads it from `aframe.io`, and this one works too.
Also, the icon isn't hosted on w3.org, that's just a part of the XML header for SVG. The image itself is embedded.
I noticed that on the working ones the `content-security-policy` is this: `upgrade-insecure-requests; default-src 'unsafe-inline' 'unsafe-eval' 'self' data: blob: *`
and on your one: `upgrade-insecure-requests; default-src 'unsafe-inline' 'unsafe-eval' 'self' blob: *`
Notice that there is no `data:`.

**Comment by evhan55** [comment]
Is the liooli.space site you linked to also hosted? on neocities?

And yeah, I don't do anything other than link to
`<script src="https://aframe.io/releases/0.5.0/aframe.min.js"></script>`

In my header, so I have no idea about all those `content-security-policy` properties you describe, I am not doing anything there, it's coming from aframe.io.

**Comment by joppiesaus** [comment]
Yes liooil.space is hosted on Neocities. The `content-security-policy` header originates from Neocities. I also am not an expert on `content-security-policy`. But I think the lack of `data:`(in combination with the current header) restricts the browser to allow `data` links.

**Comment by evhan55** [comment]
Okay, this is all useful information, thank you so much!  I will look at your source code more closely and see what is different from mine!  Thank you very much for your detailed help!

If I discover anything I will report back.

**Comment by joppiesaus** [comment]
I don't think the issue is in your code; I think the issue is in the `content-security-policy` header that is strangely different at your site. I think you'll need to await for response from someone at Neocities who knows their stuff ;)

**Comment by evhan55** [comment]
Yeah, that makes total sense.
Are you a paid subscriber/user to neocities?
I am on a free account.

**Comment by joppiesaus** [comment]
Yeah I am; but the "correct" header is also on the normal unpaid accounts.
Could it be because your site is entirely new and there is some magical glitch at neocitiesss??

**Comment by evhan55** [comment]
Okay, thanks for the info.
Yes, could be, then :(
@kyledrake paging you here just in case it's useful. Thank you!

**Comment by kyledrake** [comment]
@evhan55 @joppiesaus Give it a go, should be working now.

**Comment by evhan55** [comment]
@kyledrake Oh great, thank you very much!  I really love neocities!
