### ISSUE TITLE
The default browse page isn't being actively updated with the Most Followed list

### ISSUE THREAD

**Issue by DrEvilBrain** [neocities/neocities#221]
When at the [normal browse page](https://neocities.org/browse), the order the entries at in are not the same as the Most Followed order which it most closely resembles. I'm assuming its supposed to be in the Most Followed order since the default option is Most Followed.

Because the order isn't correct, when clicking on the site to go into surf mode, the site doesn't redirect to the proper site. Instead it redirects to the site that occupies the same slot in Most Followed order. For instance, [Lily's Flower Garden!](https://neocities.org/site/lilyblossom) directs to [D-M Adventure](https://neocities.org/site/d-m-adventure) because D-M Adventure occupies slot 21 in the Most Followed order and Lily's Flower Garden! is in slot 21 in the default browse page order.

**Comment by kyledrake** [comment]
Thanks for the report! I've temporarily disabled the surf bar until we can get a better idea of what's going on here.

**Comment by DrEvilBrain** [comment]
@kyledrake Hey what I've noticed is that clicking on the website titles on the browse page still redirect to surf mode. I'm not on a device I can make write any code with, but it looks like [line 93 of browse.erb ](https://github.com/neocities/neocities/blob/233b6f758a93fb7b69c0efe69e4f95532d651268/views/browse.erb#L93) is to blame. Shouldn't be much harder than adding the same if and else statements added before.

**Comment by joppiesaus** [comment]
@DrEvilBrain #227 fixes that issue
