### ISSUE TITLE
Cannot delete a comment

### ISSUE THREAD

**Issue by finkiki** [neocities/neocities#228]
I wrote a comment in _Activity_ and cannot delte it even after Ctrl+F5 or deconnect/reconnect.

Comment URL : https://neocities.org/site/openbooks?event_id=222091

**Comment by TomatoHentai** [comment]
You're not the only one experiencing this, me [and a few others](http://i.imgur.com/rLHIvgw.png) are having this happen too. I'd imagine there's more people having issues as well.

**Comment by kyledrake** [comment]
Sorry for the delay on this - it's been fixed.
