### ISSUE TITLE
Delete a neocitiesops.net archive

### ISSUE THREAD

**Issue by rymcbr** [neocities/neocities#230]
I took down a site about a year ago but the neocitiesops.net archive remains. Deleting a site from neocities should remove it from the archive server

**Comment by kyledrake** [comment]
I've solved this by adding a header on the server telling google not to index.

**Comment by rymcbr** [comment]
Thank you, I greatly appreciate that.

On Mar 1, 2017 11:31 PM, "Kyle Drake" <notifications@github.com> wrote:

I've solved this by adding a header on the server telling google not to
index.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/neocities/neocities/issues/230#issuecomment-283553392>,
or mute the thread
