### ISSUE TITLE
make filenames case insensitive

### ISSUE THREAD

**Issue by maycamp** [neocities/neocities#231]
If a page is typed into the address bar that is not the same casing as the file that is saved, users are sent to the 'page not found' page. This shouldn't happen.

Example: Page called test.html
Typing in username.neocities.org/Test.html will send users to 'page not found' page.

**Comment by rognoni** [comment]
> There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive.

https://www.w3.org/TR/WD-html40-970708/htmlweb.html

**Comment by kyledrake** [comment]
I'm going to wontfix this one, as it's standard that they can be sensitive. Thanks for the idea!
