### ISSUE TITLE
"Could not find a site with this username and token" when resetting password

### ISSUE THREAD

**Issue by tomatohentai** [neocities/neocities#235]
I tried to log back into my Neocities account a few minutes ago after having switched browsers, causing me to lose all my cookies, and found that I couldn't log in. I went to reset my password. The password reset link I was sent is apparently invalid, because every time I click on it, I'm redirected to the homepage and it gives me the error "Could not find a site with this username and token." I think this happened last time too, but that time I eventually ended up getting the right password after spending more time than I should've trying as many passwords as I could remember.

**Comment by kyledrake** [comment]
If you're still having issues with this, please contact support.
