### ISSUE TITLE
Communicate/advertise (with) the fact that you support HTTP/2

### ISSUE THREAD

**Issue by rugk** [neocities/neocities#236]
[HTTP/2](https://en.wikipedia.org/wiki/HTTP/2) is a very easy and effective way to decrease your site load.

**Comment by joppiesaus** [comment]
When I go to a neocities site with the network panel open(in Chrome), I see that the protocol is is "h2" and not "http/1.1". I think that means that HTTP/2 is already enabled on neocities.

**Comment by rugk** [comment]
Wow, your right! I should have checked this before… 

I'll change the topic… 😄

**Comment by kyledrake** [comment]
I've put this on the front page, and I'll add it to the compare in a little bit. Thanks for the suggestion!
