### ISSUE TITLE
Performance: Use Brotli

### ISSUE THREAD

**Issue by rugk** [neocities/neocities#237]
A new, clever and effective caching mechanism: https://google.github.io/brotli/

browser support: http://caniuse.com/#feat=brotli

setup help: https://scotthelme.co.uk/brotli-compression/

**Comment by Retroity** [comment]
According to caniuse.com, around 22.12% of the web can't use it. That means that over 1/5th of the web would not be able to use this. I would suggest waiting until this has much more compatibility.

**Comment by rugk** [comment]
Why? All browser which cannot use this just fallback to gzip, if that is available, so there is no disadvantage of using it.

**Comment by kyledrake** [comment]
I've decided to not go with brotli for now. The speed/size numbers look unimpressive. Basically we would only get a ~9% reduction for text-based assets (which are less than 5% of our total bandwidth usage) for the same speed of compression: https://blogs.akamai.com/2016/02/understanding-brotlis-potential.html

The only way to see a considerable improvement would be to jack up the compression level, but then it becomes very slow, and likely not so great for performance on the browser side. If we were to do that as a "cached" asset, then we would need to figure out how to combine that with our current cache purge system. It's going to be a lot of work and I don't think we'll see much of a benefit for it.

Perhaps in the future when the library improves, but I can't justify the additional code to make this work right now.

Thanks for the suggestion! It was interesting to learn more about it though.

**Comment by rugk** [comment]
According to Scott Helme it may be up to 33% for HTML…

> and likely not so great for performance on the browser side

Decompression is fast AFAIK. So the best would really be best to use static compression with the highest compression level.

But anyway, maybe later…
