### ISSUE TITLE
Auto-save forms

### ISSUE THREAD

**Issue by rugk** [neocities/neocities#240]
Some competitions offer this. (e.g. https://www.bitballoon.com/)
By adding a class to your forms or so they automatically adjust them and save the submission results in a database.

Of course this feature should be optional or e.g. only available to supporter accounts.

**Comment by kyledrake** [comment]
This would make people dependent on our backend, which I don't want to encourage. It would also lead to massive amounts of phishing attacks.

Thanks for the suggestion, but we're static hosting and we're proud of it. Not interested in dynamic backend stuff at all.

**Comment by rugk** [comment]
The example site I mentioned is also a static-hosting site. Anyway I get you point and I can certainly live without this feature.
