### ISSUE TITLE
cant sign in or sign up

### ISSUE THREAD

**Issue by legokiddo** [neocities/neocities#247]
so the problem started when i **ACCIDENTALLY** signed out. so i thought, no biggie ill just sign back in.
started signing back in and then it throws me back to the main page. waht?
emailed support got no answer
HELP!!!!

OS: Windows 10
Browser: Chrome

**Comment by legokiddo** [comment]
@kyledrake

**Comment by kyledrake** [comment]
Please use our support contact, not github issues for login issues.
