### ISSUE TITLE
In the editor page if file name is too long tools will go under the editor

### ISSUE THREAD

**Issue by Jackerty** [neocities/neocities#249]
http://imgur.com/gallery/hkZJf
Happens because _row.editor_ class has _position: absolute_ and _top:105px_.
Fix in Firefox while inspecting: remove _position_ and _top_ attributes and put _height: 100%_.

PS: shouldn't #153 be closed?

**Comment by kyledrake** [comment]
Your proposal seems to take care of it. Thank you!

**Comment by kyledrake** [comment]
Unfortunately I had to revert back - the change was causing the editor window to overflow past the screen. I'm not sure what else to try to fix this, suggestions welcome.

You must be using a small screen to have this happen?

**Comment by lohikaarme** [comment]
I had two firefoxes open side by side at the time.

**Comment by kyledrake** [comment]
I'm going to be revisiting all of this with #134
