### ISSUE TITLE
Promote the Python API

### ISSUE THREAD

**Issue by kwill** [neocities/neocities#259]
**User story:** I am a Python developer interested in maintaining a Neocities site. I'd prefer to use a Python API, because I am already familiar with Python.

**Suggested solution:**

* Add https://github.com/neocities/python-neocities to https://neocities.org/api
* Upload `python-neocities` to https://pypi.python.org

**Notes:**

It looks like there's an outstanding pull request for that API:
https://github.com/neocities/python-neocities/pull/1

**Comment by kyledrake** [comment]
Thanks for the suggestion! I've linked to that repo.
