### ISSUE TITLE
Can't find /privacy and /legal on live homepage

### ISSUE THREAD

**Issue by daveloyall** [neocities/neocities#261]
Using the source code here on github, I was able to find these two URLs:

* https://neocities.org/privacy
* https://neocities.org/legal

However, I wasn't able to find links to those pages on the Neocities home page.

**Comment by kyledrake** [comment]
I linked to the privacy page from the terms page, so that is now linked. The legal guide is more of a FAQ that is linked from the /contact page, for people that want to send us dumb legal threats without quite pondering the implications of that.

Thanks!
