### ISSUE TITLE
Who owns content hosted on Neocities?

### ISSUE THREAD

**Issue by daveloyall** [neocities/neocities#262]
I recommended Neocities to a friend.  He gave me this reply:

> One of the issues I have with "free" hosting is that the fine print in the user agreement often gives them full rights to your content.

Is there a published document that I can show him to allay his concerns?

**Comment by Retroity** [comment]
It looks like there isn't anything mentioning who controls the content uploaded by users in the TOS or the /legal page. The only mentions of user generated content in those pages only state that you shouldn't upload content that is prohibited and that Neocities isn't responsible for whatever users upload.

So right now, at least on the public legal pages, the answer is ambiguous. It would be great if @kyledrake could clarify this.

**Comment by kyledrake** [comment]
Neocities doesn't "own" uploaded content and we don't want to. I'm sure there's a better legal way to describe this, but I'm not, for example, assuming copyright on web sites hosted on Neocities. I'll try to figure out how to describe this better on our legal page, but I hope this works for now.
