### ISSUE TITLE
Custom domains are kept for deleted sites

### ISSUE THREAD

**Issue by sysdharma** [neocities/neocities#265]
Trying to use on a new site a custom domain which was used on a deleted site results in the following error:

"Domain provided is already being used by another site, please choose another."

**Comment by sysdharma** [comment]
Looking at the code (I'm unfamiliar with Ruby), a work-around seems to be adding a  circumvented by adding a ".exclude(is_deleted: true)" to https://github.com/neocities/neocities/blob/3aea4e833370f8685afe00500a5abaa4baab1c77/models/site.rb#L1029

But I'm not sure if the redirection configuration is ignoring deleted sites, so this could result in duplicate redirection configs for the web server.

**Comment by sysdharma** [comment]
Well, I tried accessing the deleted site by url and the redirection still works, so I'm afraid the work-around I mentioned would indeed result in a duplicate redirection configuration. Let me find that code next.

**Comment by sysdharma** [comment]
While looking for the redirection code, I found this (https://github.com/neocities/neocities/blob/93b333dbf258af8a2754b360ae78dd61d2141519/views/templates/email/domain_fail.erb) which makes me believe there is a worker trying to detect these broken custom domains - I'm unsure if it is working though.

**Comment by sysdharma** [comment]
To answer my previous question, yes, the worker which detects these broken custom domains is the letsencrypt worker:

https://github.com/neocities/neocities/blob/3ff6f420a4fe8c989f17bff561a8034431478d17/workers/lets_encrypt_worker.rb#L159

But it does not help at all when the site is deleted because of:

https://github.com/neocities/neocities/blob/3ff6f420a4fe8c989f17bff561a8034431478d17/workers/lets_encrypt_worker.rb#L33

**Comment by sysdharma** [comment]
Another thing I just learned while reading the code. Although the delete site page says "There is no undo! Be very sure you want to do this.", if you try to signing using the site name and password, it allows you to recover the site (and remove the custom domain). Because of the contradiction if messages (no undo vs. can undo), I'm unsure this is working as intended.

**Comment by sysdharma** [comment]
One option to fix this, in the Site model define another delete method, similar to the one in ParanoidDelete

https://github.com/neocities/neocities/blob/ce905200da6de473e85041fccfc4e82d687365ab/ext/sequel/plugins/paranoid_delete.rb#L10

But also set the :domain value to an empty string.

**Comment by sysdharma** [comment]
Two other options:

Before calling destroy, set an empty domain value:

https://github.com/neocities/neocities/blob/68352e3d8fdf8e24390973e06b24e98088d698ab/app/settings.rb#L37

Or in before_destroy, in the same transaction, set the empty domain value:

https://github.com/neocities/neocities/blob/3aea4e833370f8685afe00500a5abaa4baab1c77/models/site.rb#L446

(IMO this last one seems to be the best one, but I'm not a Ruby programmer or familiar enough with the code to be comfortable submitting a PR).

**Comment by kyledrake** [comment]
Apologies for the delay here. I believe I have a fix for this now. If you're having a specific issue with a specific domain still, please let me know at https://neocities.org/contact.
