### ISSUE TITLE
Invalid SSH certificate for www custom subdomain

### ISSUE THREAD

**Issue by pmlt** [neocities/neocities#270]
Hello, 

I have configured a custom domain for my neocities website (philmilot.com). I followed the instructions to setup a www subdomain for the same site (using a CNAME record), but the SSH certificate being served there is only valid for philmilot.com and not its subdomains.

Did I do anything wrong?

**Comment by Retroity** [comment]
www.philmilot.com seems to be working for me and correctly redirects to philmilot.com (without the "www" subdomain)

Is it not working for you?

**Comment by pmlt** [comment]
It works when going through http://www.philmilot.com, but https://www.philmilot.com gives a NET::ERR_CERT_COMMON_NAME_INVALID error on Chrome, and SSL_ERROR_BAD_CERT_DOMAIN on Firefox.

**Comment by Retroity** [comment]
Ah, I see what you mean now. That's odd, considering that my Neocities site doesn't have this problem (https://www.retroity.net works for me but https://www.philmilot.com doesn't)

@kyledrake Is there any reason why this is happening?

**Comment by kyledrake** [comment]
Aye, yes. There's this weird issue where the www record doesn't appear when the root domain is validated. I'm working on some code to improve this and to check with the controlling nameserver, etc. I might just require a www CNAME and check for both an A and CNAME record going forward.

The basic fix is to run it a little later. I'm trying this hotfix for now: https://github.com/neocities/neocities/commit/693c07914e23c0e690af86c750215b856367afc6

I'll keep working on this, but for now your problem with the www has been resolved.
