### ISSUE TITLE
email confirmation code

### ISSUE THREAD

**Issue by asiazaiser** [neocities/neocities#271]
signed up two days ago and still have yet to receive my confirmation code to create my account. double checked email and also junk folder

**Comment by minegamer5570** [comment]
Try re-sending if that is available... I had this issue with other services in the past...

**Comment by kyledrake** [comment]
Yeah uhm, it works and every time I've checked it it continues to work. Not sure if there's an ISP spam blocker issue with some machines or not, but yeah... it works on our end, and I can't really fix something that's not broken on my end.
