### ISSUE TITLE
Broken "Invalid Tags" error message!

### ISSUE THREAD

**Issue by Kiddo9000** [neocities/neocities#276]
Messing around with tags on a site. I got an error because i use an invalid character and the error message didn't look right... It looked like something from https://www.reddit.com/r/softwaregore. I think you guys put the quotes in the wrong places... Just thought you should know... Here's an image:

![hhhhhhhhhhhhh](https://user-images.githubusercontent.com/29239155/39634195-2689c83e-4f88-11e8-894b-0bf14fb0735c.PNG)

**Comment by minegamer5570** [comment]
I'm gonna close this as it seems the error doesn't even appear anymore and rather displays nothing. Also tags with just 2 spaces in them will go through and appear on the website's profile.

**Comment by kyledrake** [comment]
Got this taken care of, thanks for the report.
