### ISSUE TITLE
Can I build a private site in Neocities ?

### ISSUE THREAD

**Issue by funny110** [neocities/neocities#279]
I don't want my site auto share to `Global Activity`. Only the people I share can visit my site.

**Comment by dotcomboom** [comment]
You can go to Settings > Manage Sites > Profile and disable your site profile and comments.

People will still be able to visit your site with the URL, but this hides your site from the rest of Neocities.

**Comment by topotech** [comment]
From the FAQ in their contact page:

"[W]e sometimes see people trying to use .htaccess for authentication (with usernames and passwords). **Neocities is only for sites and information you want to make public, and it is dangerous to use it for private sites! We make backups of your site and attackers can easily find any information you're trying to hide using our archivers.** Our goal is to make sure your sites stay up for a long time and persist, not to enforce secrecy zones on your site. **If you want to make a controlled access site, Neocities is not for you.**"
