### ISSUE TITLE
Invalid ssl

### ISSUE THREAD

**Issue by scobiehague** [neocities/neocities#280]
When I visit my custom domain driftshell.com (intended to replace scobiehague.neocities.org) the lock icon in Firefox is not green. SSL info reports "This website does not supply ownership information."

My namecheap config for custom domain:

https://imgur.com/a/aRXkUlO

I'm wondering if I configured my domain settings wrong, but seem to remember these settings working in the past. 

Entering scobiehague.neocities.org tries to redirect to driftshell.com and also receives ssl errors. 

Thanks for looking.

**Comment by kyledrake** [comment]
I'm not sure what happened here, but I updated it manually and that seems to have resolved it. I'll keep looking into what happened to see if I can prevent this in the future.
