### ISSUE TITLE
Editing profile comments not working

### ISSUE THREAD

**Issue by dotcomboom** [neocities/neocities#281]
Browser is Firefox 61.0.1.

On my user profile, there is an "Edit" link, however when clicking the link, nothing happens, and the link just disappears.

![broken editing](https://user-images.githubusercontent.com/38927017/43295604-046a62fe-9114-11e8-9135-5d799fc54645.gif)

**Comment by BigBallerBrand2** [comment]
Same here on Chrome 68. I've tried on other browsers like Firefox, Opera, and Safari, but still doesn't work.

**Comment by 14jammar** [comment]
I don't think the edit option has _ever_ worked at all.

Also it is quite a nice day.

**Comment by BigBallerBrand2** [comment]
It certainly is!

**Comment by kyledrake** [comment]
Resolved with https://github.com/neocities/neocities/commit/c5d019494659411f230b7644de72d7511ae2a49d
