### ISSUE TITLE
Support pdf as allowed file type

### ISSUE THREAD

**Issue by Serkan-devel** [neocities/neocities#282]
Maybe someone wants to link to a scientific paper from it's blog

**Comment by 14jammar** [comment]
It is an allowed file type, as seen on [this page](https://bananachan.neocities.org/BriansPath.html), in fact you don't even need to be a supporter to upload a PDF file.

If you can't upload a PDF file, you [should contact Kyle about this](https://neocities.org/contact).

**Comment by Serkan-devel** [comment]
But wait, is this page from a supporter account?

**Comment by 14jammar** [comment]
@Serkan-devel Bananachan is [not a supporter](https://neocities.org/site/bananachan). I was also able to upload a PDF on my Hyperlink webhome, as seen [here](https://hyperlink.neocities.org/owlman/meme.pdf). [Hyperlink is not a supporter site](https://neocities.org/site/hyperlink).
