### ISSUE TITLE
Backspace in Mobile Editor works intermittently

### ISSUE THREAD

**Issue by elaboraet** [neocities/neocities#284]
When using the online NeoCities text/code editor on a mobile device, **deleting characters (backspace) works for a number of characters at first, but then gets 'stuck,'** requiring you to enter, say, a space, and then continue deleting characters before it gets stuck again, requiring the above mentioned "fix" to keep it going.

I have tried this on Firefox and Samsung Internet on a Galaxy S8. Requesting the desktop version of the site usually worked better. The keyboard I was using was NextApp Technical Keyboard found on Google Play, but I had also tried it with the default Samsung keyboard, though not shown in the video.

Here is a video I uploaded from my device for reference on the issue if there is anything I missed. https://peertube.xyz/videos/watch/bf83ae0f-1301-4e9b-b0b6-30f273683c7f

**Comment by 14jammar** [comment]
When I went to school, some people would play "punchie", a game where the first person would punch the second person, then the second would punch the first, but harder, etc. I guess in the year of 2018, people hurt their selves by using the Neocities' mobile editor.

Also, the link of the video doesn't work, I suggest uploading it to YouTube, or something like that.

**Comment by elaboraet** [comment]
@14jammar - I have now uploaded the video to BitChute. It should be visible/working now.

Also, what editor would you recommend if I weren't to use the default editor?

**Comment by elaboraet** [comment]
@14jammar - Of course; I compose everything on a PC unless I am somewhere without it.

I was thinking that you were suggesting a different desktop editor.

Nonetheless, editing on mobile would be much easier if this backspace issue was not present.
