### ISSUE TITLE
Remove jerk detection

### ISSUE THREAD

**Issue by dotcomboom** [neocities/neocities#289]
How it is right now: **2** people block someone, and now they can't post on anyone else's walls.

This can be abused so, so badly. Speaking of how someone can just whip up two email accounts and shadowban somebody permanently. People block others when *they* don't want to hear what they have to say; just because *they* don't want to see someone on Neocities, it doesn't mean they should be able to take away their ability to communicate.

Asking for a friend.

**Comment by kyledrake** [comment]
I made some changes to this to fix some issues and make it harder to abuse it (see the commit), which indeed has removed some sites on this that shouldn't have been there.

Hopefully this improves things, but I'm not going to outright remove it. Looking at the users with the highest number of blocks has demonstrated that it is infact working quite well to help prevent a few bad actors (namely trolls and spam lords) from turning Neocities into Twitter-style toxic waste dumpster. If I was to 100% remove this, I would probably instead likely replace it with a requirement that someone needs to follow the other person before the other person can start posting on their feed. So we'll go with these changes and I'll keep monitoring to see if there's further changes that need to be made here.

**Comment by kyledrake** [comment]
But definitely thank you for bringing this up, it did need to be addressed. :+1:
