### ISSUE TITLE
ipfs automatic archiving of sites doesn't appear to be working

### ISSUE THREAD

**Issue by rodoviario** [neocities/neocities#291]
I have created a site for a linux user group, and made changes to it, but it doesn't show the "archived versions" nor the ipfs hash

**Comment by da2x** [comment]
This is a duplicate of #156.

**Comment by jeremyredhead** [comment]
@da2x I don't think this is actually a dup of that?

@rodoviario They previously had IPFS archiving enabled by default, but they recently (when?) forcibly disabled it by default for everyone, this retroactively purging countless archives 😠 
(to be fair it was always experimental)

Anyway, you can re-enable it in your site settings.

**Comment by kyledrake** [comment]
Indeed this has been switched over to opt-in. I've gotten the archiver working again, hopefully with the opt-in setting things will be a lot more stable.
