### ISSUE TITLE
Directory uploads with files with identical names in different directories messes up

### ISSUE THREAD

**Issue by TheLastZombie** [neocities/neocities#296]
Title. When I try uploading a folder (dragging it into the dashboard) that has the following directory structure (example):
```
Folder
├─── Subfolder 1
│    └─── image.png
└─── Subfolder 2
     └─── image.png
```
The image from Subfolder 2 gets uploaded into Subfolder 1 and the file from Subfolder 1 doesn't get uploaded at all.

I'm using Firefox 65.0, should this matter.

**Comment by kyledrake** [comment]
Thank you, this was a serious bug and it has now been resolved with https://github.com/neocities/neocities/commit/2c5ef5195be770abd6ae8b4fc0f1694e1be91cfb
