### ISSUE TITLE
Directories not supported

### ISSUE THREAD

**Issue by tanyagray** [neocities/neocities#3]
Directories cannot be created or uploaded. Additionally, attempting to drag-and-drop a folder into the upload area produces an unfriendly error.

**Use case:**
Doing local dev and making use of 'images', 'css' and 'js' folders as is best practice results in a site which is incompatible with upload to Neocities :(

**Comment by aaronransley** [comment]
Hoping that I'm not beating a dead horse here, but am curious about directories as well. Would like to automate publishes via the [neocities module](https://www.npmjs.com/package/neocities).
