### ISSUE TITLE
Site vanished and not allowing to login further

### ISSUE THREAD

**Issue by catchme1412** [neocities/neocities#301]
While I was working on my site, I was thrown out of the site. After that, I was not able to access my account or site. When I try to reset the password using the token I get "Could not find a site with this username and token.".

**Comment by topotech** [comment]
As a sidenote from your bug report: I'm just an user like you, but maybe you should try to [contact](https://neocities.org/contact) them directly, since your problem in particular seems to have more to do with the integrity of their users table in their database. Good luck!

**Comment by catchme1412** [comment]
I already tried to contact, but no response. I guess neocities.org is not maintained properly. I have decided to move out to some other web hosting services.
