### ISSUE TITLE
Support preprocessors for user sites

### ISSUE THREAD

**Issue by aurium** [neocities/neocities#303]
It would be nice to publish a `.pug`, `.sass`, or `.coffee` files and view the resulting `.html`, `.css`, or `.js` files on the web.
I believe it could work safely like this:
1. GET `file.html`
2. Is there `file.html`? Yes: respond with `file.html`. No: continue ...
3. Is there `file.[pug, haml, md]`? No: respond with 404. Yes: continue ...
4. Generate `file.html` (not in the user's directory. In the cache directory)
5. Reply with cached `file.html`

**Comment by aurium** [comment]
GET `file.[pug, haml, md, coffee,...]` should return itself _(not the converted version)_, to alow client-side hacking.

**Comment by Serkan-devel** [comment]
That more or less defeats the point of a static file host.
I'm pretty shure you can transpile these types of files locally and upload those instead.

You can automate that process and upload via the API

**Comment by aurium** [comment]
I understand you. I can do this, but i want to help kids that can't.

The "static file host" feature still ok if it transpiles the comiplable files on upload. (And ignore my GET description).

I believe it will be realy nice allowing people to use a simpler (or better) language in the neocities's web editor.

**Comment by Serkan-devel** [comment]
But Neocities seems to bring back [web 1.0](https://websiteconf.neocities.org/). Back then, there weren't really transpilers as we know it today.

Maybe children could learn simpler web development from the 90' that way.

**Comment by aurium** [comment]
I don't call the 90's way simpler, even though I started there. 😁
Well, i agree an static result is a good thing and also necessary to the IPFS feature. So if there is a problem, i could help to think or also to implement in ruby.

**Comment by kyledrake** [comment]
There is a part of me that likes this, and I've thought of it before, but I have a standing golden rule of not adding anything to Neocities that wouldn't exist on a static web host. I don't want people to become dependent on Neocities backend for their sites to work.

Thank you for the suggestion! It's just a little out of our philosophical wheelhouse, thought I agree it would be nice.
