### ISSUE TITLE
Please whitelist XML based syndication file formats

### ISSUE THREAD

**Issue by da2x** [neocities/neocities#304]
XML files are allowed, but common syndication file extensions aren’t on the whitelist. Is this an oversight or intentional? Maybe whitelist by content types instead of extensions? Allowing `text/*`, `application/xml`, and `application/*+xml` would cover all of these:

- [ ] .atom
- [ ] .opml
- [ ] .rdf
- [ ] .rss
- [x] .xml

**Comment by kyledrake** [comment]
Added them to the whitelist
