### ISSUE TITLE
SSL certificate issue 

### ISSUE THREAD

**Issue by halipalombo** [neocities/neocities#306]
Hi, when I try to navigate to my website I get this error:

"Your connection is not private
Attackers might be trying to steal your information from halipalombo.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID

This server could not prove that it is halipalombo.com; its security certificate is from *.neocities.org. This may be caused by a misconfiguration or an attacker intercepting your connection."

Any idea how to fix this? Thank you

**Comment by kyledrake** [comment]
It's been resolved.

**Comment by beak-tama** [comment]
Hi, I am also getting this message every now and then as well

**Comment by kevinhdw** [comment]
Hi I am also encountering this message
![image](https://github.com/neocities/neocities/assets/99868795/e0dacab2-8127-4e84-b56b-d6e1a3d478be)

**Comment by kyledrake** [comment]
@kevinhdw send an email to contact(&)neocities.org I need to ask you information to debug this that shouldn't be public (like your IP address).
