### ISSUE TITLE
Orange(biggest ISP in Poland) is blocking Neocities

### ISSUE THREAD

**Issue by FenekAlfa** [neocities/neocities#308]
As title says, I can't connect to any Neocities site(including support)

For a few days now, Firefox has been giving an Secure Connection Failed error without any explanation. I thought it might just be acting up for whatever reason and tried opening the site in links. Here's the blocking message:

> CyberTarcza Orange Orange Polska                                                                                                                                                           
>                                                                                                                                                                                            
>Uwaga, zagrożenie                                                                                                                                                                             
>                                                                                                                                                                                              
>  CyberTarcza Orange powstrzymała próbę phishingu!                                                                                                                                           
>                                                                                                                                                                                              >   Widzisz tę stronę, ponieważ prawdopodobnie kliknąłeś/aś w podejrzany link w mailu lub na stronie internetowej. Strona, na którą próbujesz wejść, to potwierdzona witryna phishingowa,      
>   próbująca wyłudzić od Ciebie dane logowania do systemu e-bankowości. Próba wejścia na fałszywą stronę została zablokowana przez CyberTarczę. Właściwy adres strony banku znajdziesz        
>   poniżej.                                                                                                                                                                                   
>                                                                                                                                                                                             
>   Powiązany serwis: mBank                                                                                                                                                                    
>   Zły adres: https://*.neocities.org                                                                                                                                                         
>   Prawidłowy adres: https://www.mbank.pl/                                                                                                                                                    
>   (adres nie jest klikalny – zaznacz go kursorem, skopiuj i wklej do przeglądarki)                                                                                                           
>                                                                                                                                                                                              
>   Jak nie zostać ofiarą phishingu?                                                                                                                                                           >                                
>Jak uniknąć zagrożenia?                                                                                                                                                                       
> By upewnić się, że niniejsza informacja pochodzi od Orange Polska, sprawdź certyfikat strony, klikając w nazwę Orange Polska S.A. jak na poniższych przykładach:                           
>                                                                                                                                                                                             
>Chrome                                                                                                                                                                                        
>                                                                                                                                                                                              
>Firefox                                                                                                                                                                                       
>                                                                                                                                                                                             
>Internet Explorer IE                                                                                                                                                                           >                                                                                                                                                                                              >  (c) 2015 Copyright Orange Polska S.A.                                                                                                                                                      
>  Kontakt z CERT OPL: cert.opl@orange.com                                                                                                                                                    > TI FIRST                

Basically, Orange is blocking all Neocities URLs, claiming you're involved in phishing mBank users. What most likely happened is that someone set up a page that did it and Orange thought the whole site was about phishing.

**Comment by kyledrake** [comment]
I'm closing this because this is only for issues related to the Neocities source code, not technical support.

Regardless, if some terrible ISP in Poland has decided to block a major platform and doesn't understand how browser security origins work there's really not much I can do about that. I guess you could give me the ASN from here and I could try to contact their NOC: https://bgp.he.net/. You might want to just try calling them, because I don't speak polish and will probably have a very hard time trying to explain the problem to them...

**Comment by kyledrake** [comment]
I just emailed with their NOC and it appears to be resolved. Thanks for
bringing this to my attention.

**Comment by kyledrake** [comment]
(ps: sorry if I came off as a little cranky...)
