### ISSUE TITLE
HTTP Error: Too Many Requests

### ISSUE THREAD

**Issue by RenFinkle** [neocities/neocities#312]
Feel free to just close this if this isn't the place for this question. 

I'm trying to connect to davs://neocities.org/webdav via nautilus in Ubuntu 18.04 and I was able to do this (albeit very slowly) yesterday, however today I'm getting this message:

![image](https://user-images.githubusercontent.com/11714575/64491891-691e2f00-d23b-11e9-8fc6-ebc854e4bd97.png)

**Comment by kyledrake** [comment]
Please contact neocities support so we can figure out the specifics of this: contact@neocities.org
