### ISSUE TITLE
Would it be a good idea to put neocities onto the public suffix list?

### ISSUE THREAD

**Issue by sixcorners** [neocities/neocities#318]
https://publicsuffix.org/learn/
I guess this can prevent supercookies from being created and things like that.

**Comment by kyledrake** [comment]
I was told it would make cookies not work on the root domain (neocities.org), so I would either need to move the sites to a different domain (neocities.io) or move the root to a subdomain (www.neocities.org), neither of which are super appealing to me, so I decided not to pursue it.

**Comment by qgustavor** [comment]
I'm also worried about this. Isn't possible to add `*.neocities.org`, but not `neocities.org`, and add an exception to `www.neocities.org` and other subdomains which users aren't allowed to use. The [format it uses](https://github.com/publicsuffix/list/wiki/Format#example) allows for wildcards and exceptions.
