### ISSUE TITLE
Problematic drag and drop

### ISSUE THREAD

**Issue by stefanos82** [neocities/neocities#331]
First of all, great job! :+1: 

A few minutes ago, I have generated my static website via hugo and have tried to drag and drop my entire generated content, but for some reason would not upload all files or folders in a recursive way.

I had to take file by file and folder by folder separately to upload them on my site.

Is this the expected behavior?

**Comment by evenkei** [comment]
I had a similar experience trying to upload a hugo site! Certain files would be missing, and I believe a few corrupted files appeared where they should not have been. I'd love to hear if there are any insights into this!

**Comment by insanitywholesale** [comment]
I encountered the same thing. dragged and dropped the files generated by hugo into the uploader and then any folder that had folders in it was messed up, files were in places they should not have been. it seems especially problematic for folders with folders inside them

**Comment by jackomix** [comment]
I had the same experience uploading a local version of my site. I was wondering why my site seemed to take up a lot more space than I thought, lol.
