### ISSUE TITLE
WAIT NO NEVERMIND I FOUND THIS OUT ON MY OWN

### ISSUE THREAD

**Issue by eIysian** [neocities/neocities#351]
not too sure if people are still actively on this page but is there any way to change the tags of your website? i made my account on neocities over a year ago and the tags are kinda embarrassing and aren't exactly related to my site. any help would be appreciated!

**Comment by p1zzboyx** [comment]
how did you fix it?

**Comment by ValdikSS** [comment]
Please close the issue (use "close" button under the comment field).

**Comment by haydenwalker980** [comment]
Pointless issue, OP hasn't closed this, can we get somebody with contributor perms like @kyledrake to do so?
