### ISSUE TITLE
IPFS archiving does not work, no content seeders, stalls websurfing with IPFS companion extension

### ISSUE THREAD

**Issue by ValdikSS** [neocities/neocities#352]
Neocities IPFS archiving functionality has been broken at least since August 2019. No peers are seeding websites' content in IPFS. `ipfs dht getprovs` command returns nothing on all websites I have tried it.

Any IPFS-enabled Neocities website can't be opened with public IPFS gateway. Both IPFS and IPNS links do not work.
Example: `fauux.neocities.org`
IPFS link: http://gateway.ipfs.io/ipfs/QmVV41XY3BTmqtKe6egyqu74B8YojTSW9ScnSeLH4jyyxP
IPNS link: http://gateway.ipfs.io/ipns/fauux.neocities.org

**Users of IPFS Companion browser extension will get redirected to IPFS gateway, rendering Neocities websites which have IPFS enabled in the site settings inaccessible.**

**If IPFS functionality is broken without any plans for repair, please disable IPFS archiving for Neocities websites (to remove `dnslink` record to IPFS on all domains).**

This has been reported to Neocities tech support somewhere in August 2019, as well as to @kyledrake directly over email, without any reply.

**Comment by insanity54** [comment]
I've just been bit by this issue. The build of my site served by IPFS is 4 months old and it seems there's nothing I can do about it. I disabled IPFS archiving for my site and there is no effect; visitors with IPFS enabled browsers are still served the outdated build.

**Comment by mdonoughe** [comment]
It seems like there are multiple issues with the IPFS integration. I tried making a new site to see if I could create a tool that can load an archive of the site into IPFS with the same content ID so you could seed your own site, but IPFS defaulted to disabled and even after checking the box to enable it and modifying the site, my site does not have a DNSLink record or any IPFS archives listed in settings. It doesn't look like you can export somebody else's site except via IPFS, but maybe I could find a simple site which doesn't have any hidden files and just wget it.

Of the top 100 sites, 56 have a DNSLink record. None of those have any seeders.

**Comment by jeremyredhead** [comment]
It looks like [IPFS was disabled in the update to Ruby 3](https://github.com/neocities/neocities/commit/0ca1473d22d78171f5e40ad06852cb7555d71f40#diff-e9c799cf3be9ddb3a5b8aa3b49ce8b4c4ae5941fc6e6cef15a6ebe57b4574ea9)
I guess there was some problem to fix & Kyle just never got around to fixing it?

**Comment by sysfu** [comment]
> It looks like [IPFS was disabled in the update to Ruby 3](https://github.com/neocities/neocities/commit/0ca1473d22d78171f5e40ad06852cb7555d71f40#diff-e9c799cf3be9ddb3a5b8aa3b49ce8b4c4ae5941fc6e6cef15a6ebe57b4574ea9) I guess there was some problem to fix & Kyle just never got around to fixing it?
> 
> After paying closer attention, I'm guessing it has to do with the [Rye gem](https://github.com/delano/rye) which hasn't seen an update since 2015(!) and was commented out. So if someone can figure out what's wrong there and fix it we should be one step closer to restoring IPFS support

Thanks for digging up that info-nugget. IPFS support was a big selling point for me so hoping this feature comes back sooner rather than later.

**Comment by kyledrake** [comment]
Hello, not everyone is going to love hearing this but we're deprecating IPFS support from Neocities. I'll spare everyone the giant rant and just say that the tech and strategy of how to implement it has moved in a different direction that I don't think makes it a good choice for what I wanted to do with it with Neocities, and I don't really have any meaningful access to the process at this point so I can't really do anything about it except walk away. At the same time, Neocities is getting very busy (we just hit 700k sites) and I really need to corral the wagons and focus on the bread and butter stuff for now.

My apologies to anyone that was here specifically for the IPFS support.

**Comment by mdonoughe** [comment]
Will all the Neocities subdomains have their DNSLink records cleared so IPFS users don't get redirected to old versions of the page which are not being seeded?

**Comment by kyledrake** [comment]
@mdonoughe yes the DNSlink records have already been removed.
