### ISSUE TITLE
Issue uploading .js files (zepto.min.js, touch.js)

### ISSUE THREAD

**Issue by eibol** [neocities/neocities#38]
Hi, I have been testing successfully the site with a free account (eibolmooc), and I have found out that sometimes uploading fails with certain files (.js, .png). It has happened with a free account, and I was uploading to a folder some files that were already in the root folder. I test either upload button and drag & drop feature with same results.

I also tried those to upload the same files to my supporter account (eibol), and did not experience these issues.

Thanks for checking
Best regards
Abel

**Comment by kyledrake** [comment]
Could you email the file to me at kyledrake@gmail.com? I need the files not working in order to figure out why the whitelister is rejecting them.

Thanks!

**Comment by eibol** [comment]
I have the sent the files, I hope they arrived properly.
Cheers

**Comment by eibol** [comment]
I just created a new neocities account to test and the issue did not show up, weird. Something related to eibolmooc account then.

**Comment by kyledrake** [comment]
I just uploaded using your files, and I am not able to reproduce this bug.

What OS and browser name/version are you using? Does it give any error messages, or just fail silently?

**Comment by eibol** [comment]
I tried Windows 7 latest with Firefox /Chrome, and Ubuntu 14 with Firefox.
I have reproduced the bug in this screencast, using Windows 7 and Firefox 35.0.1 spanish version. I could not try english versions yet.

http://eibol.neocities.org/Neocities_Upload_bug.mp4

**Comment by eibol** [comment]
I tried yesterday different upload combinations and issue seems to be solved. Thanks.
