### ISSUE TITLE
Neocities won't let you edit SVGs with the text editor

### ISSUE THREAD

**Issue by ro1y** [neocities/neocities#387]
SVGs have their own manually editable syntax. Why don't they get an option to be edited like html and css files?

**Comment by linux-leo** [comment]
I agree, just had this problem today, no need for syntax highlighting, but being able to edit them at all would be nice.

**Comment by joppiesaus** [comment]
One (ugly) workaround is to manually enter an URL: `https://neocities.org/site_files/text_editor/<filename>` will open the web editor with file `<filename>`
