### ISSUE TITLE
Unblock button not working

### ISSUE THREAD

**Issue by KateYagi** [neocities/neocities#392]
Hi, my site is kateyagi.neocities.org.
I recently blocked a site, but realised pretty quickly I misjudged them and wanted to unblock them, but the button doesn't seem to work as intended, just scrolling to the top of the page, but the site remains blocked even after refreshing the page, and re-logging in.

Browser: Ungoogled Chromium
I turned off uBlock so it's probably not that.

**Comment by necrophcodr** [comment]
@KateYagi This seems to be fixed as of 6ea07df6a84c7cd5591f690ed75b7808ebd7a532 . I can't verify if it is live or not, but if it is, could you close the issue?

**Comment by KateYagi** [comment]
> @KateYagi This seems to be fixed as of [6ea07df](https://github.com/neocities/neocities/commit/6ea07df6a84c7cd5591f690ed75b7808ebd7a532) . I can't verify if it is live or not, but if it is, could you close the issue?

Can confirm unblocking works now. Closing.
