### ISSUE TITLE
Issues with expired SSL certificates/older devices

### ISSUE THREAD

**Issue by jax-js** [neocities/neocities#401]
Hello!
I'm trying to make my site accessible to older devices (like the DSi or the PSP) but I ran into a problem while trying to do this since Neocities forces SSL/doesn't accept expired SSL certificates.

Is it possible to disable SSL encryption on my Neocities site?

**Comment by joppiesaus** [comment]
no

**Comment by M-Valentino** [comment]
I don't think Neocities is meant to be this technical. At a certain point, you might as well use AWS S3 buckets.

**Comment by kyledrake** [comment]
I covered this with a new-ish FAQ tab:

We recommend using an "old web browser" proxy server like [WebOne](https://github.com/atauenis/webone) or [WRP](https://github.com/tenox7/wrp). These translate between modern browser standards and old browser standards, allowing for us to provide the speed and security of the new web without compromising the ability to use old browsers

The thing is, with old browsers all of the new sites are going to fail to render anyways, so if we weaken SSL it doesn't really change that. It's much better to use a old browser proxy anyways, better experience overall.

I think it would be kindof cool to provide this proxy for people doing this as a service but I don't know how practical that would be.
