### ISSUE TITLE
Unblock button doesn't work

### ISSUE THREAD

**Issue by Morrowseeer** [neocities/neocities#416]
Read the title, when you block a site (example:
![s60jHibxFQ](https://user-images.githubusercontent.com/93443315/192653097-4cae81ac-eb37-4612-a5de-81a891def91c.gif)

All it does is act like a "return to top" button, making unblocking a site actually impossible.
Using the latest version of Chrome, apparently it also happens on Firefox too.

**Comment by JakenHerman** [comment]
Looks like that `href` is set to `"#"`, so yes - the unblock button will not work.

File: `neocities/views/site.erb`
Lines: `107-111`
``` erb
         <% if current_site && current_site.is_blocking?(site) %>
            <a href="#">Unblock</a>
          <% else %>
            <a href="#block" data-toggle="modal">Block Site</a>
          <% end %>
```

Similarly, [`neocities/app/site.rb`](https://github.com/neocities/neocities/blob/master/app/site.rb) does not seem to have an unblock function.

@kyledrake happy to help out, if you'd like.

**Comment by kyledrake** [comment]
Resolved, should work now.
