### ISSUE TITLE
Tutorial page → dead links

### ISSUE THREAD

**Issue by Brin-o** [neocities/neocities#419]
The [tutorial page](https://neocities.org/tutorials) has a few broken/non https links. 

The dead links should probably be replaced with something else, the non http links prompt a security warning on both safari and firefox.

Dead: http://codepupil.com
Non HTTPS: https://www.htmldog.com/guides/html/beginner

**Comment by jeremyredhead** [comment]
The whole tutorial page needs a new lick of paint IMHO.
*All* of the HTML tutorial links are http: except for MDN (but all currently seem to support https, except CodePupil ofc).

HTML:
- CodePupil is in the Wayback machine but it doesn't quite seem to work, sadly.
- I don't know if it was like this in 2013, but Treehouse now only offers a 7 day free trial which **requires a credit card**. Hmm
- Codecademy redirects to a page chock full of backend stuff, which is irrelevant to Neocities (and maybe overwhelming for noobies?). The specific HTML course could be directly linked to instead: https://www.codecademy.com/learn/learn-html

Both CSS & JS only have MDN listed for learning resources. 
Codecademy has a JS and CSS course (but only the JS one is free). 
There are *tons* of other JS resources; there are also probably a few other good CSS resources?
