### ISSUE TITLE
Redirect /page/ to /page

### ISSUE THREAD

**Issue by jeremyredhead** [neocities/neocities#435]
This is technically an issue with the nginx config (which I guess is a trade secret maybe? I'd love to see it :),
and [I've mentioned I'm not happy with the .html stripping](https://twitter.com/jeremyredhead/status/1622031879011536898),
but this would at least make it a little more... symmetrical, and allow those who had previously been making a directory + index.html for every page to *safely* transition to the new method.

Neocities currently redirects /dir to /dir/ so I assume the reverse is possible in Nginx.
It would, I assume, complexify things slightly since you'd have to check that /page.html exists but /page/ doesn't (tho I assume again the inverse is already true?)

Please feel free to close if it isn't possible or not something you're interested in doing.

**Comment by flamedfury** [comment]
I'm keen for flexibility in redirects. I have my RSS feed at `/feed.xml`. My previous host resolved both `/feed.xml` and `/feed.xml/`. 

Since moving to Neocities `/feed.xml/` 404, a bunch of people who had the `/` in their feed readers are now getting a big fat error.

**Comment by kyledrake** [comment]
This isn't really practical to change at this point unfortunately, apologies.
