### ISSUE TITLE
it's hard to click on "edit" or "delete" files on the dashboard

### ISSUE THREAD

**Issue by ghost** [neocities/neocities#439]
there could be an UI improvement regarding this, cause it gets very annoying having to click half a dozen times on "delete" or "edit" while it keeps opening the file itself instead of deleting/editing it.

**Comment by alephdfilms** [comment]
Did you try using the List View?

**Comment by cyberhardt** [comment]
> Did you try using the List View?

oh, you're right, it's much better. they could improve the regular view nonetheless.

**Comment by kyledrake** [comment]
Going to try #516 for resolving this, thanks everyone for the feedback.
