### ISSUE TITLE
Weird website

### ISSUE THREAD

**Issue by BETTEY-developers** [neocities/neocities#449]
When I open my website, the browser is display a warning. 
![image](https://user-images.githubusercontent.com/78239044/236197938-d06f30ee-e96b-438e-b9fe-d06fb83a1694.png)
ps. Sorry I'm from Chinese. Only upload the chinese pictures:(
Now some neocities website icon is weird.
![image](https://user-images.githubusercontent.com/78239044/236198371-0c53cc47-8ab3-45f2-980a-e8496efb59e6.png)

**Comment by kyledrake** [comment]
It looks like the government firewall is inserting a fake SSL cert for this particular subdomain

![Screenshot from 2023-06-26 09-56-11](https://github.com/neocities/neocities/assets/28153/6a9bc431-f105-4530-acdb-e474b2a6a904)

The reason they would do this would be to man in the middle the connection, for what reason can only speculate.

I'm not seeing this for the main Neocities site, or for other subdomains. I didn't know they could do it on a subdomain level actually, I assumed they would block our whole platform as soon as something made them mad.

Unfortunately there's not really much I can do here, this issue means that our strict SSL cert system is working as designed, to prevent MITM attacks.
