### ISSUE TITLE
Total API meltdown when trying to parse an upload target with [ square brackets ]

### ISSUE THREAD

**Issue by Hug-Animals** [neocities/neocities#456]
Works:
`curl -F "foo.webp=@/tmp/[filename].webp" <credentials>`

Also Works:
`curl -F "bar/foo.webp=@/tmp/[filename].webp" <credentials>`

Produces Error: "foo.webp" appears, not "[foo.webp"
`curl -F "[foo.webp=@/tmp/[filename].webp" <credentials>`

Throws Error: 
`curl -F "bar/[foo.webp=@/tmp/[filename].webp" <credentials>`

```
{
  "result": "error", https://github.com/neocities/neocities/blob/master/app/api.rb#L47
  "error_type": "missing_files",
  "message": "you must provide files to upload"
}
```

Code in Question:
https://github.com/neocities/neocities/blob/master/app/api.rb#L47

**Comment by Hug-Animals** [comment]
Its worth noting, that I tried escaping the brackets using both \ and % escapes, with no success. I could not find a workaround, and was not able to use neocities-cli to make this work either. It produced the same result.

**Comment by FrogCast** [comment]
Has this issue been resolved... much less even looked at?
I pay for this site and they have literally zero support.

**Comment by kyledrake** [comment]
Thanks for your patience https://github.com/neocities/neocities/commit/e7e5121700b832b2673b957d92dc0111959ff32f
