### ISSUE TITLE
Scale jerk filter threshold with follower count

### ISSUE THREAD

**Issue by PencilVoid** [neocities/neocities#468]
Follower count is a sufficient measure of reputability in most cases. While the current threshold of 25 is enough to prevent most sites with small or medium popularity from getting unjustly filtered, large sites are still able to reach this amount of blocks without necessarily carrying out antisocial behaviour towards others. In fact, antisocial behaviour may not be the only reason someone would block another user; they may simply not be interested in that user's site and prefer not to see it in their feed if possible. Having the threshold for the jerk filter to activate scale with the account's number of followers would accommodate for this and reduce the number of users who are unfairly filtered.

**Comment by kyledrake** [comment]
Thanks for the idea, we'll go with this and see if it needs tuning https://github.com/neocities/neocities/commit/19dadfd6d224fc35634bd2dc0828846109e838b6
