### ISSUE TITLE
File Support (IMPORTANT!)

### ISSUE THREAD

**Issue by waylon-20** [neocities/neocities#469]
Can you please make it so that me and others can use .MP3, 4 and .MIDI . I (and others) Would Really and i mean _**Really**_ like it.

**Comment by wiichicken** [comment]
I think you have to pay to upload those files in order to prevent piracy. Reasonable enough for me.

**Comment by sharkota** [comment]
> Can you please make it so that me and others can use .MP3, 4 and .MIDI . I (and others) Would Really and i mean _**Really**_ like it.

You can use a file hosting service like dropbox as a CDN if you want. I think its fair enough to make some files supporter only.

**Comment by kyledrake** [comment]
MIDI is already supported, but yeah we're not going to support mp3/4 for free accounts. Way too many piracy concerns still unfortunately, apologies.

**Comment by waylon-20** [comment]
So, MIDI is supported! Ok! Thanks for the help!
