### ISSUE TITLE
WebDAV on Windows 7 may not be working

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#47]
A user has reported that they were having trouble mounting WebDAV on their Windows 7 machine.

```
I tried to create the new network drive, and entered
https://neocities.org/webdav
as the network address to use.  Windows tried to connect to that address for ~15 seconds, and then reported that "The folder you entered does not appear to be valid."

I've tried debugging this for a while, but so far without any luck.  I can connect to the WebDav address using my browser, but not by adding a network location or mapping a network drive.
```

Relevant links:
http://www.onemetric.com.au/Documentation/Mounting-A-WebDAV-Share-Windows-7
https://social.technet.microsoft.com/forums/windows/en-US/67c361c0-ed6a-4e82-81df-da149c96492b/webdav
http://support.microsoft.com/kb/2560598

Mapping a network drive didn't fix this either, as the third article suggests.

**Comment by kyledrake** [comment]
I'd love it if someone with Windows 7 was able to test this and see if it works, I don't have Windows 7 handy. Thanks!

**Comment by kyledrake** [comment]
I'm not sure what we can do about this, so I'm closing. We've got an note on the contact page that there may be issues here.

**Comment by westdale** [comment]
I get the same behaviour on Windows 10
My primary site is accessible via Firefox and https://neocities.org/webdav with my password.
I note as a side issue that there seems to be no way to access my second site.
Happy to do some simple testing if you can tell me what you want done.

**Comment by mendelevium** [comment]
Windows 10 native tool does not support HTTPS addresses. Users must install [NetDrive](http://www.netdrive.net/download/) or some other WebDAV client in order to properly map a drive through a secure connection.

**Comment by kyledrake** [comment]
@mendelevium Thank you for figuring this out. It's completely irresponsible for Microsoft to not provide HTTPS support for WebDAV, there's no way we'll ever support unencrypted WebDAV access.

I'll make a note on the docs.

**Comment by westdale** [comment]
Thanks for sorting out this puzzle

**Comment by westdale** [comment]
Connected easily with NetDrive!

Only snag is that access to html page through Firefox or Chrome is 
incredibly slow.
This seems to be true whether the webdav link is set as network drive or 
local drive.

Do you have any suggestions?

**Comment by mendelevium** [comment]
@westdale just edit files locally and overwrite them on the drive when you're done (never a good idea to edit a live website)

**Comment by westdale** [comment]
Thanks for responding - yes I agree with your point, Martin - the master 
copy is on my data drive locally and edited using coffeecup (or textpad 
if I want to do a regex edit).

I was actually referring to browsing the local drive link to the website 
using FFox or Chrome - deadly slow.
Reading other comments on the web, I find it is a 'known issue' with webdav.

**Comment by Retroity** [comment]
I know this is an old issue, but mounting Neocities using Windows 10 appears to work now. I successfully mounted my site. Can provide proof if needed.
