### ISSUE TITLE
Enable Cross Origin Isolation (Godot embeds don't work without it)

### ISSUE THREAD

**Issue by jacekjarosz55** [neocities/neocities#471]

**Comment by kyledrake** [comment]
I need a better description to move forward here, it's not clear to me what the issue here is. We do have a configured cross origin policy already.

**Comment by jacekjarosz55** [comment]
I hope you don't mind if I reopen this issue. Godot Engine 4 web exported games use SharedArrayBuffer, which is disabled on browsers by default, unless `self.isOriginIsolated == true`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements
https://web.dev/articles/cross-origin-isolation-guide
