### ISSUE TITLE
Injected Open Graph meta tags interferes with already existing ones

### ISSUE THREAD

**Issue by hf02** [neocities/neocities#476]
It seems that Neocities now injects Open Graph tags if the user agent is detected to be a bot. However, if your website already has Open Graph tags, they interfere and give inconsistent results across platforms.

## Example

With [a plain webpage I created for this issue](https://dabric.neocities.org/ogp-test).

It displays my metadata on Discord:

![image](https://github.com/neocities/neocities/assets/55464333/7bfc1014-7d1d-4e2a-b284-298063886a91)

However, it displays Neocities' injected metadata on Signal.

![image](https://github.com/neocities/neocities/assets/55464333/92080d3d-17c4-4f8a-ac37-0b5647d1e54d)

## Solution

Perhaps something similar to GitHub Pages' `.nojekyll` to show that you don't want the meta tags, so you can have full creative control over your webpage.

**Comment by hf02** [comment]
Found a workaround. You can break it by putting a space in the head's closing tag, causing no meta tags to be injected:

```html
<head>
    <!-- ... -->
</head >
```

You can see it working on [Nu HTML checker with Discordbot's user agent](https://validator.w3.org/nu/?showsource=yes&useragent=Mozilla%2F5.0+%28compatible%3B+Discordbot%2F2.0%3B+%2Bhttps%3A%2F%2Fdiscordapp.com%29&acceptlanguage=&doc=https%3A%2F%2Fdabric.neocities.org%2Ftest2%2Fmetatags-test).

**Comment by kyledrake** [comment]
The reason specifically that your example is not working is because it's not correctly formed open graph meta. See the spec here: https://ogp.me/

It is possible that your version works on certain sites but it is not supposed to work, it is the incorrect properties, per the spec.

I'm resolving this issue by being a lot more liberal with how the og detection works, which should resolve this and similar issues (a bunch of newlines in the tag, single quotes vs double). Expect this to be deployed in the next few days.

**Comment by hf02** [comment]
> The reason specifically that your example is not working is because it's not correctly formed open graph meta. See the spec here: https://ogp.me/

Oh my god I feel dumb. Thanks!

**Comment by kyledrake** [comment]
> > The reason specifically that your example is not working is because it's not correctly formed open graph meta. See the spec here: https://ogp.me/
> 
> Oh my god I feel dumb. Thanks!

No worries, I think your way also works in practice, likely most people support it as an extra thing even though it isn't documented.

Regardless the newlines are also an issue with our detection. The new approach is we're just going to look for "og:image" and friends as just a string without checking for meta, head, or location of that, and if we see it at all, we won't inject the data.
