### ISSUE TITLE
Replies / Comments just stopped working

### ISSUE THREAD

**Issue by jacekjarosz55** [neocities/neocities#479]
Upon clicking 'reply' or 'comment', it just jumps to the top of the page, not doing anything.

**Comment by jacekjarosz55** [comment]
could be related to commit 837b0ea2d0380617918253812c4266e5ac52b84d perhaps?

**Comment by jacekjarosz55** [comment]
![image](https://github.com/neocities/neocities/assets/72438686/40878b72-304f-47e2-8a3a-43d302484860)

**Comment by kyledrake** [comment]
Thanks for the report, this has been resolved (related to CSP changes, which are finding a surprising amount of 'unsafe-eval' stuff in our old code (the particular issue here was underscorejs).
