### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by violasong** [neocities/neocities#48]
At some point, we may want to consider having some sort of code of conduct or anti-harassment policy. There would need to be one set of guidelines for site comments and conduct within the company/open source project, and a looser set of guidelines for individual sites since those are basically the user's own space.

- Let people know that if they ever feel unsafe they can contact us or flag the offending account
- Acknowledge that this can be a serious problem for social networks and tech organizations 
- Point out that online threats and websites dedicated to tormenting an individual are illegal by [US state laws](http://www.ncsl.org/research/telecommunications-and-information-technology/cyberstalking-and-cyberharassment-laws.aspx)
- Balance our existing open company and free speech goals with pro-diversity goals

Related to issue #18

**Comment by kyledrake** [comment]
This is a good idea. This might be a good starting point: http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy

**Comment by violasong** [comment]
Done! https://github.com/neocities/neocities/blob/master/code-of-conduct.txt

**Comment by kyledrake** [comment]
:+1:
