### ISSUE TITLE
Share button on the HTML editor is too prominent and too easy to hit by mistake

### ISSUE THREAD

**Issue by gammalogic** [neocities/neocities#482]
It would be great if the "Share" button at the top-right of the HTML editor window could be moved away from the "Save" and "View" controls as I keep clicking on it by accident. This button would make more sense if it was in the file browser view as a overlay when moving the cursor over individual files.

**Comment by kyledrake** [comment]
Thanks for the feedback. I didn't move the button but I have a pending commit to add icons to each of the buttons which should make them harder to misidentify. You can also use ctrl+s to save with the keyboard as a shortcut too (i should probably express this somewhere).

**Comment by gammalogic** [comment]
Thanks Kyle.
