### ISSUE TITLE
Step 8 of coding tutorial won't accept link text with a space

### ISSUE THREAD

**Issue by lindenmori** [neocities/neocities#488]
The [tutorial ](https://neocities.org/tutorial/html/8)did not accept this in step 8:
`<li><a href="link removed">mori kei</a> coords</li>`
showing an error message that I need to give the link a name between the <a> tags. However it accepted
`<li><a href="link removed">mori</a> coords</li>` .

**Comment by kyledrake** [comment]
Fixed this, thanks
