### ISSUE TITLE
Recursive drag-and-drop not working

### ISSUE THREAD

**Issue by dei-layborer** [neocities/neocities#491]
I saw the previous issue about this (#157), but unfortunately it's still not working (even on Chrome).  If I drag a folder with subfolders to upload it, it gets rid of the subfolders and just puts everything in the "root" of the folder I've uploaded.

Definitely a pain when dealing with larger sites.  For example, I'm trying to upload one created by Hugo right now, and there're a few layers in some parts of it.

I'm using Chrome version 121.0.6167.139 (arm64) on macOS 14.1.

**Comment by Proxybat** [comment]
Hi I'm also having this issue! I'm using firefox 123.0 (64-bit) on a windows 11 computer.

If I drag and drop a folder that has subfolders to upload it, it does the same thing as this issue. The subfolder gets deleted while the files from the subfolder get placed into the parent folder.  So it does something like shown below.

**Folder on my computer:**
``` md
# test-folder
- **sub-folder**
  - image-1.png
  - image-2.png
  - image-3.png
- image-a.png
- image-b.png
```
**Folder when uploaded onto neocites via drag and drop:**
``` md
# test-folder
- image-1.png
- image-2.png
- image-3.png
- image-a.png
- image-b.png
```

I feel like this is a major issue for users who use many subfolders for any reason. I hope that sharing this brings more attention to this issue.

**Comment by kyledrake** [comment]
It's coming along: https://github.com/neocities/neocities/commit/943271b50921bd522a4236ba20fde102547cf5e8

**Comment by kyledrake** [comment]
Finished: #497
