### ISSUE TITLE
Enhancement: Improving readability of drag and drop text in the site editor

### ISSUE THREAD

**Issue by M-Valentino** [neocities/neocities#502]
You can barely read the helper text in the drag and drop upload:
<img width="1088" alt="Screenshot 2024-03-14 at 10 22 24 PM" src="https://github.com/neocities/neocities/assets/79779618/1d5a6183-5750-4191-9377-18a4f1e78865">

I made this mockup of how it could be improved but I have mixed feelings on it:
<img width="1088" alt="neocities drag and drop mockup" src="https://github.com/neocities/neocities/assets/79779618/2556048d-e7ba-42f8-b891-c9cb967619ad">
It is much more readable and the color matches the teal color of the navigation bar, but it stands out too much. Maybe instead of it being centered vertically and horizontally, it could be centered and placed inside the dotted border, but on the bottom.

**Comment by kyledrake** [comment]
I think I'm going to leave it as-is. It's initially hard to read I agree, but it's a one time thing just to give users instructions that they can do drag and drop on that element, and then it kind of disappears into the background. Thank you for the idea though!

**Comment by kyledrake** [comment]
(I might try to give it a gray hue at some point or something though.. if you have any ideas feel free to comment!
