### ISSUE TITLE
Trying to upload/edit json and js files says I need supporter.

### ISSUE THREAD

**Issue by Nyarumiku** [neocities/neocities#504]
I have a gallery on my website and it needs a json file that I can no longer edit or upload a new copy of it.
It was working already but now it suddenly says I need supporter
The supported files page says they are supported, did something change?
![image](https://github.com/neocities/neocities/assets/164560718/e710b9a7-322f-476e-b796-112d67587394)

Infact there's already json/js files on my website but if I try to edit those it wont let me either.
![image](https://github.com/neocities/neocities/assets/164560718/8a333ac1-2820-42be-b03a-8d7fcfb28a6a)
![image](https://github.com/neocities/neocities/assets/164560718/b5703d19-3797-4a87-84c5-0a6a4b6d04d0)

**Comment by kyledrake** [comment]
Can you attach the files you're having trouble with? Thanks

**Comment by kyledrake** [comment]
Nevermind I think I've figured it out, working on it

**Comment by kyledrake** [comment]
Should be fixed, thanks for the report. TLDR, mime type got changed after switching to the api for uploading via the dashboard.

**Comment by Nyarumiku** [comment]
It's working now, Thanks for the help!
