### ISSUE TITLE
Git push deploys

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#52]
Allow users to "git push" deploys to Neocities.

**Comment by chris-l** [comment]
+1 Yes please!

**Comment by phikal** [comment]
:+1: What's the progress on this?

**Comment by ffdd** [comment]
+1

**Comment by kyledrake** [comment]
I ended up doing this with the git hooks and the neocities-cli https://neocities.org/cli
Much easier/safer than running a full git interface on Neocities...
