### ISSUE TITLE
Stop blocked users from liking your posts

### ISSUE THREAD

**Issue by divSelector** [neocities/neocities#520]
The way it currently is, someone you've blocked can still send you a simple message that basically says, "I'm watching everything you do," by liking all of your posts. This is problematic because if you've blocked someone, it's most likely because they have over stepped and are making you uncomfortable.

**Comment by divSelector** [comment]
https://github.com/neocities/neocities/pull/521

**Comment by kyledrake** [comment]
Just an FYI that I removed personal identifiable information - if you have a specific concern about a specific user please contact support. I'm laser focused on keeping the github issues code only.

I agree that a blocked user should not be able to do this, and really a blocked user should not even see posts from who blocked them either. I'll probably update the code to deal with that.

**Comment by kyledrake** [comment]
Hopefully solved with https://github.com/neocities/neocities/commit/0531a1d85fd2b0d7b1fa333669230f867dd83f89
