### ISSUE TITLE
Confirming phone number is impossible.

### ISSUE THREAD

**Issue by AnDruStein** [neocities/neocities#524]
<img width="375" alt="firefox_gQdARSOwM9" src="https://github.com/neocities/neocities/assets/37749418/2611d445-c788-478a-a80d-399dfe82e456">

So, I encountered this problem when I wanted to actually create an account. No matter how I write my phone number to this form, it doesn't accept it with "Invalid phone number, please try again." message.
For this console screenshot I also disabled all adblockers and stuff. 

Looks like intlTelInput script just fails to load. Is there some way to fix it myself or its just a bug of Neocities itself?

**Comment by kyledrake** [comment]
This is a legacy issue, please contact support and we can whitelist it for you. Thanks.
