### ISSUE TITLE
0 points for >1000 api calls?

### ISSUE THREAD

**Issue by scarecat** [neocities/neocities#525]
I think its a bit unfair to just delist someone from 'Special Sauce' for just using the api for a long time. And for what I understand from the source code, having over a 1000 api calls gives your site 0 score as a penalty. Maybe it could be a daily rate limit instead?

**Comment by scarecat** [comment]
Please correct me if i'm wrong with this assumption and the api_calls field is actually being cleared somewhere else.

**Comment by kyledrake** [comment]
Special sauce api calls for bot detection is 500k, which is a crazy amount of updates. If someone is updating this much it's likely a bot.
