### ISSUE TITLE
Sites by Last Updated seemingly now only showing sites with a lot of views

### ISSUE THREAD

**Issue by nottnottloop** [neocities/neocities#530]
Sites by Last Updated used to show (or at least feel like it showed) the latest sites updated, regardless of the visit count. I'm not sure what has changed, but now this sorting seems to only show sites with high visit counts.

**Comment by CrNTD** [comment]
The default search also turns up less sites now than it used to.

This especially affects small tags, which feel completely empty now. Sorting by "Newest" seems like the only way now to browse all sites related to a tag, but this is incredibly unintuitive.

**Comment by dimdenGD** [comment]
Related commit: https://github.com/neocities/neocities/commit/2ef0d2101c1a78df853ae1b1a32be5c7710acf0e

**Comment by kyledrake** [comment]
As @dimdenGD mentions it's not a bug, it's an intentional design change.

There has always been a minimum views requirement to be on this page (Site::BROWSE_MINIMUM_VIEWS), but I'm adding additional criteria because it's been a lot of homelab stats bots and related bad/irrelevant stuff.

I could certainly have a feature to take out the filters on everything and have the raw output of literally every last update, but it will be kind of a garbage dump and I wouldn't want to make it the default view.

I'm not sure how to move forward here, I'll leave the issue open because I can certainly tweak things. Input is welcome.

**Comment by nottnottloop** [comment]
A big part of the appeal of Neocities for me is while yes, there are big and fancier sites that have already gained traction, someone hitting F5 on Last Updated can certainly have fun on the slot machine of finding new smaller and more beginner websites too. It kind of gives a newbie hope that they can actually be discovered by those who are keeping their eyes peeled for new websites using the filtering option this exact way. I'd say that is really important, yes even your barely customised Neocities template you updated five times with some funny random text can be discovered and cherished, 'wow that was easy, I should make my own site'. Personally I didn't even notice the spam sites, it might be because I am used to tuning that stuff out of my brain. 

I couldn't find a 'Last Updated' site with less than 16k views on page 1, so I'm thinking that's a pretty hardcore threshold for a newcomer. One has the initial traffic spike if any from the 'Newest' section and then I suppose you're left wondering how someone could discover your site. I might not have noticed the extent of the botting as it was before so in my eyes the old behaviour was fine, I do think if the requirements are going to be tougher going forward the requirements should go down by a lot.

**Comment by kyledrake** [comment]
I think we all agree with your sentiment, we're just trying to find the right balance here so it doesn't look like the spawn region in 2B2T (unless you want it to).

**Comment by nottnottloop** [comment]
Maybe 500 views or something. Just a small rite of passage to actually appear on the last updated page. Hopefully this could be made transparent to users too

**Comment by kyledrake** [comment]
Consider this site for an example: https://neocities.org/site/regal

Some sort of script that updates a printer status or something.

Views limit won't get it off the updated page. Some other stuff needs to be considered.

**Comment by dimdenGD** [comment]
I own a similar site host to Neocities, and I solved this by not showing site in last updated if it was updated via API.

**Comment by nottnottloop** [comment]
Perhaps a rate limit for appearing on the updated page, you can appear there once every hour or so. I thought it was spam filling this feed but if it's these auto update sites then I understand now.

> I own a similar site host to Neocities, and I solved this by not showing site in last updated if it was updated via API.
Hopefully the Neocities CLI is protected ^^

**Comment by nottnottloop** [comment]
I'm not really sure how many of these sites are out there but if I'm not mistaken there's a moderation option for someone to flag sites as NSFW so they won't show up as publicly. There could be a 'frequent update site' flag as well, which would hide them from the feed. Not a perfect solution obviously as it needs manual intervention to stay on top of it, if the scale of the problem isn't so bad (I don't know) then it could be viable.

**Comment by kyledrake** [comment]
We do have a count tracker for API calls, but there could be people using clever site editors that way and I don't necessarily want to punish them for that. I think invalidating any sites that use an API call would inevitably have a lot of false positives on it.

What are your thoughts on something like this 
![Screenshot_2024-08-12_15-08-02](https://github.com/user-attachments/assets/f59646ad-2059-4b99-b0eb-5f6f7099b007)

**Comment by nottnottloop** [comment]
Love the idea honestly, curated experience if someone wants it or anarchy. I wonder if oldest would just stay static, and how are sites in the robots category determined

**Comment by dimdenGD** [comment]
needs Last Updated and then it'll be awesome

**Comment by kyledrake** [comment]
@dimdenGD just tossed that together quickly, but yeah it will have all the things when done.

Oldest would just stay static, which is just my friends testing the site when we launched basically. I don't think its a very useful category, but if anyone wants to see that I suppose we can make it available.

Robots would be sites with api_count greater than some arbitrary number (10,000?) for the botheads out there dying to know the current weather on Bainbridge Island, WA (like in Ray Bradbury's *All Summer in a Day*, the sun is only visible for two hours every seven years).

**Comment by kyledrake** [comment]
I'm going to be committing some changes today that don't quite do the screenshot but take out the scoring for tags and add various other refinements. I'm continuing to add things and I'll eventually get to deep cut unfiltered-ish searching but this improves things for now. It's also high time we addressed the NSFW searching problem. The main throttle there is just making the commented out NSFW checkbox on views/browse.erb look good in the UI, if anyone wants to beat me to it feel free, I've discovered a duplicate tags issue today and I need to look into that.

I'm also switching from "most followed" to "special sauce" for the first click of browse, which is mostly the same sites on top but should move some up-and-coming sites more towards the top by adding metrics other than just raw follower count, and also works to prevent follower count gaming. This is kind of my plea for people to please not get ultra pissed about the change, it's really important for the platform to promote newer also-awesome sites and not just become an ossified gerontocracy. (I'm overselling the difference, it's a pretty conservative change).

**Comment by nottnottloop** [comment]
When you say take out the scoring for tags do you mean scoring for tags assigned to sites or scoring for the categories in the dropdowns? I don't know the code that well I didn't know tags assigned to sites were scored

Making special sauce the default is a pretty good idea IMHO, not that the sites of the top of there aren't good but they have been burned into my retina every time I go to browse and that's the default category that is sorted by

**Comment by kyledrake** [comment]
The score is computed based on this formula, which re-computes daily https://github.com/neocities/neocities/blob/master/models/site.rb#L1453

I found that the tagged sites are sufficiently good that the score *filtering* isn't really necessary for tag browsing, and in fact I might even include tag presence to the algorithm in the future.

I would really really like to keep this as documented and not throw it in BlackBox with the abuse prevention code, because secret algorithms promoting dangerous garbage has been quite the conversation of society right now, so I think it's cool that we're publishing our dirty laundry by default. All algorithms are ultimately the product of taste-making by individuals, and you get to actually see my taste-making here, I'm not going to launder my responsibility for them like Facebook and Google do that it's just Robots That We Don't Have Control Over (TM). At the same time if it starts being gamed and abused though (why?! just make a good web site people will come to it!), it will go into the box (or some component of it will).

**Comment by roygbiv-temp** [comment]
Hey, sorry to bump this but I thought it would be more polite than making a new issue - is there any chance of you implementing an option to unhide things caught in the "jerk filter" and other such filters?
I'm finding it harder and harder to browse neocities over the last ~3 months as several tags I'm interested in are now entirely blank unless I check the activity feed, which doesn't accurately show all sites within a tag.
I've attached an example below, but this is beginning to get very frustrating as I can't search by tags, and instead have to navigate external spreadsheets/listings, and user follow pages to find the sites I'm interested in viewing. I can understand a potential want to hide such sites by default, but a way to disable that hide would be nice going forward ^^
![image](https://github.com/user-attachments/assets/8d8cc15c-569e-4acf-bd34-d1da52c9ea11)

best wishes, Roy G. Biv

**Comment by Cyclotrons2** [comment]
@kyledrake 
> ...it's really important for the platform to promote newer also-awesome sites and not just become an ossified gerontocracy.

I'd say that, as it is now, this system is failing to do this. [As of now](https://web.archive.org/web/20241008172909/https://neocities.org/browse?sort_by=last_updated&tag=), on the 'Last Updated' page, there isn't a single website shown that was created after this change was made.
