### ISSUE TITLE
nobody can sign up.

### ISSUE THREAD

**Issue by trinnerbinner** [neocities/neocities#536]
captcha invalid everytime no matter what.

**Comment by kyledrake** [comment]
I just tested it and it works fine. What browser are you using, are you using a phone or desktop, and are you using any browser extensions?

**Comment by Itsamejonah** [comment]
What? I don't remember making this issue!

**Comment by kyledrake** [comment]
Okay well it's working for me. I had a few complaints it wasn't working the other day, but was making some changes to the front index that may have temporarily caused it. If it's actually broken still let me know.

It does seem to be harder now than it used to be (GOOD).
