### ISSUE TITLE
Show pricing chooser after initial signup

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#54]
When users create an account, they should be directed to an initial one-time page that asks them if they would like to become a supporter, and they choose a free or supporter button, and then it continues to the news feed once they're finished.

The hope is that this increases clickthrough to supporter.

Very high priority.

**Comment by kyledrake** [comment]
Mangle /plan to do this using from_create=1 or something for now, do something better later.

**Comment by kyledrake** [comment]
Victoria will be designing a mockup for this!

**Comment by violasong** [comment]
Wrestled with it a bit more and came up with this version which better separates the two plans:
https://dl.dropboxusercontent.com/u/55342/temp/pricingwelcome04x.png

(previous version: https://dl.dropboxusercontent.com/u/55342/temp/pricingwelcome03x.png)

Will see if there's anything else I can do to it tomorrow, but I should start coding something soon.

**Comment by kyledrake** [comment]
This is perfect! +1 to coding it. :)

**Comment by violasong** [comment]
Okay! Made some final tweaks https://dl.dropboxusercontent.com/u/55342/temp/pricingwelcome05x.png

How do you want me to do this - in a mockup erb or new branch?

**Comment by kyledrake** [comment]
The mockup controllers are in app/mockups.rb right now, yeah just make a views/welcome_mockup.erb and I'll take it and make it into /welcome. Thank you!

**Comment by violasong** [comment]
Cool, I'm on it.

**Comment by violasong** [comment]
Phew, finally made some progress - still need to adjust a bunch of styles but the basic structure is there. I checked it in case you want to work on the copy at the bottom.

**Comment by violasong** [comment]
Okay, basically done - still going to tweak the css for various screen sizes but the html is stable if you want to work on it. Right now the skeuocard is just a placeholder image.

**Comment by kyledrake** [comment]
I've added an "ACTIVE" label to show which ones I'm working on right now. I'll be working on implementing this today.

**Comment by kyledrake** [comment]
Pushed. The remaining derpiness is attached.
![derpieness](https://cloud.githubusercontent.com/assets/28153/6359494/83979778-bc28-11e4-8388-d10cf01c6365.png)

**Comment by kyledrake** [comment]
A remaining nicety would be to make the upgrade button highlight when the card info is finished being filled out, but I can't find a good way to do it, so I'm passing on it for now. Might file another issue for it.

It's live - closing ticket!
