### ISSUE TITLE
Trying to build source and getting RubyVM::YJIT as an uninitialized constant

### ISSUE THREAD

**Issue by BanceDev** [neocities/neocities#541]
System: Linux Mint 22
Ruby Version: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
Bundle Version: Bundler version 2.3.10

Followed install instructions in the readme and faced the error below when attempting to run with bundle.

Also if it is just more advisable to run natively on my system since I'm on Linux Mint that works, I just need to know what dependencies I need. Thanks!

```
vagrant@ubuntu-jammy:/vagrant$ bundle exec rackup -o 0.0.0.0
/vagrant/environment.rb:2:in `<top (required)>': uninitialized constant RubyVM::YJIT (NameError)
	from /vagrant/app.rb:1:in `require'
	from /vagrant/app.rb:1:in `<top (required)>'
	from /vagrant/config.ru:2:in `require'
	from /vagrant/config.ru:2:in `block in <main>'
	from /var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/builder.rb:116:in `eval'
	from /var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/builder.rb:116:in `new_from_string'
	from /var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/builder.rb:105:in `load_file'
	from /var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/builder.rb:66:in `parse_file'
	from /var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/server.rb:249:in `app'
	from /var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/server.rb:422:in `wrapped_app'
	from /var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/server.rb:312:in `block in start'
	from /var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/server.rb:379:in `handle_profiling'
	from /var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/server.rb:311:in `start'
	from /var/lib/gems/3.0.0/gems/rack-2.2.9/lib/rack/server.rb:168:in `start'
	from /var/lib/gems/3.0.0/gems/rack-2.2.9/bin/rackup:5:in `<top (required)>'
	from /usr/local/bin/rackup:25:in `load'
	from /usr/local/bin/rackup:25:in `<main>'
```

**Comment by BanceDev** [comment]
I also had to install many of the dependencies myself inside the vagrant vm to even get to this point. When I try a fresh install it does not have all the correct dependencies and bundle install doesn't even install all of them without throwing errors.

**Comment by BanceDev** [comment]
I did a full reinstall of the vm to get a better idea of the issue. I had to run``` vagrant up --provision``` twice to even be able to run vagrant ssh. Here are the logs from both of those commands.
[vagrant.log](https://github.com/user-attachments/files/17017714/vagrant.log)
[vagrant2.log](https://github.com/user-attachments/files/17017715/vagrant2.log)

**Comment by BanceDev** [comment]
I was able to just convert the shell scripts for my linux mint machine for a local setup after some tweaking. Gonna leave this issue open for now tho in case that this is problematic for other contributors.

**Comment by Itsamejonah** [comment]
dance till your dead
