### ISSUE TITLE
Recent update removed text editor themes?

### ISSUE THREAD

**Issue by Trashpanda115** [neocities/neocities#546]
I want to discuss the most recent Neocities frontend update, which appears to have removed several of the themes, including the theme I myself personally use, and I would also like to politely ask if there is any chance we can get them back?
Earlier this day, I edited my website as usual, using my theme, which I believe was under the name of "Terminal Dark"
However, I come back to edit some more, and my theme has been swapped to "All Hallows Eve" and my previously mentioned "Terminal Dark" theme is just gone. I looked through the entire scroll of themes and couldn't even find a single theme that had anything similar to my previous theme, and I want to at least know why and would like to politely inquire as to if we can get these back, as I am finding it really difficult now to even think about editing my site, due to the entire text based editor feeling wrong because the colours are no longer the ones I am familiar with.
-Roxanne S.

**Comment by kyledrake** [comment]
Restoring old themes.. might be possible but it involves finding a theme for Monaco (aka vscode) or figuring out some way  to convert from Ace editor themes to Monaco. I'll take a look at it tomorrow but I can't guarantee anything right now.

**Comment by BanceDev** [comment]
I know there are ways to make themes manually. It’s a bit of effort but if there’s enough need for it in particular cases I could look into throwing smth together.

**Comment by kyledrake** [comment]
The easiest way to do this might just be to add back something close-ish from the already available themes: https://vscodethemes.com/

@Trashpanda115 if you found a theme in that list that you think would be a sufficient replacement we could add it and it. Given how popular monaco/vsc is I'm assuming there's themes for every preference at this point.

**Comment by kyledrake** [comment]
Let's move this discussion to https://github.com/neocities/neocities/issues/543
