### ISSUE TITLE
Recent Feature/Feature Request: Allow users to configure Monaco editor suggestions

### ISSUE THREAD

**Issue by ammon-m** [neocities/neocities#548]
Could this change be reworked into a configurable option, if it isn't currently broken?

I know that Neocities users have used the text editor with no suggestions for years, and many have lived comfortably this way.
However, there are also many individuals on this platform who are used to using code completion and suggestions in their daily work, such as in the vscode editor, whom may become annoyed by the feature being disabled when working on their website.

To prevent the need to force one group to follow another's preferences, there could be a persistent option to toggle suggestions added to the text editor, so that the end user can use the behavior that they prefer.

No worries if this never happens. While I usually prefer suggestions, it doesn't hurt me much to be without them.

Relevant Commit: 3b97b3f89cfa8dcff923caeb267aad0383a8f590

Relevant Pull Request: #547

**Comment by kyledrake** [comment]
Can you move this to #543 please? Thank you.

**Comment by ammon-m** [comment]
oh silly me, sorry
