### ISSUE TITLE
Claim @neocities on Twitter

### ISSUE THREAD

**Issue by violasong** [neocities/neocities#55]
Submit trademark report https://support.twitter.com/forms/trademark

In the report, we should ask if Twitter can just rename @neocitiesweb to @neocities so that it keeps all our current followers/tweets. (There's also a hackier way to make this happen.)

**Comment by kyledrake** [comment]
I tried this, and received the following letter from Twitter:

> Hello,
 
> We've researched the reported account and determined that it is not in violation of Twitter's Trademark Policy. The account is not being used in a way that is misleading or confusing with regard to its brand, location or business affiliation.

> Twitter does not have a username reservation policy. Users are free to select any name for their account, provided they do not violate Twitter's Terms of Service or Rules.

> For more information about Twitter's Trademark Policy, please see:

> http://support.twitter.com/articles/18367 
 
> Thanks,
 
> Twitter

Not sure there's much more I can do here, unfortunately. Closing for now.

**Comment by kyledrake** [comment]
I should note for future record researchers that this is basically a dead account - someone registered @neocities and then basically abandoned it, but Twitter still won't give us the name. If this was an active user, I probably wouldn't have filed a trademark complaint.

**Comment by kyledrake** [comment]
OK, weird idea. I'll message the account user and see if they'll give it to us. Since it's a dead account, I don't expect a response, but I'll reopen if the dead rise.

**Comment by kyledrake** [comment]
I forgot that I can't message people on Twitter without them following me. Nevermind.
