### ISSUE TITLE
Fix site profile main content area background issue 

### ISSUE THREAD

**Issue by violasong** [neocities/neocities#65]
As seen here: https://neocities.org/site/steampunkdream

Relevant commit: https://github.com/neocities/neocities/commit/84beecac20df0e978af2819ab0ef48301af5ea76

**Comment by kyledrake** [comment]
I'm not seeing it. Could you post a screenshot?

**Comment by violasong** [comment]
![screen shot 2015-03-01 at 3 36 23 pm](https://cloud.githubusercontent.com/assets/55994/6432969/dd98c400-c028-11e4-9bb8-38f90d72e311.png)
Only happens when there's an unusually short main content column. I know how to fix this but the new timeline view I'm working on will probably make this not a problem.

**Comment by kyledrake** [comment]
ok!

**Comment by kyledrake** [comment]
Is this still an issue?

**Comment by violasong** [comment]
It will effectively be fixed once the more graphical news feed is implemented, so I'll close this in anticipation of that happening
