### ISSUE TITLE
Improve top navigation bar

### ISSUE THREAD

**Issue by violasong** [neocities/neocities#73]
- The named "Neocities" link only shows up on the homepage when signed in, which is odd.
- Kinda seems like there are too many links in it. About, Tutorial, or API could potentially be moved to the bottom for now.

**Comment by violasong** [comment]
Okay, the too many links thing is bugging me :). @kyledrake, are you okay with me removing: 
- Text link to "Neocities" (only appears on signed-in homepage)
- "About" (I think it's okay to just have that at the bottom, open to other suggestions though!)

**Comment by violasong** [comment]
Oh, "Neocities" also appears in the non-signed-in homepage when you scroll down. Probably not necessary though...

**Comment by kyledrake** [comment]
Feel free to re-arrange things up there any way you'd like.

I noticed that when you add more links to the bottom the layout for the footer gets messed up, so you may want to look into that too.

**Comment by violasong** [comment]
Are you just talking about the way it wraps? I could adjust the ratios on the columns there.

**Comment by kyledrake** [comment]
Not sure, I just recall that adding more links breaks the footer. Might be a wrapping issue, yeah.

**Comment by violasong** [comment]
Okay, adjusted the margins. If more than one or two extra links need to be added, we'll have to shorten the text in the left column - maybe change "Follow us on Twitter or Facebook" part to just icons.
