### ISSUE TITLE
Design a more graphically rich timeline view (news feed)

### ISSUE THREAD

**Issue by violasong** [neocities/neocities#76]
- Display small screenshots for social actions
- Maybe much larger screenshots for site updates, since people only seem to change up to four things at a time

**Comment by violasong** [comment]
Initial ideas: https://dl.dropboxusercontent.com/u/55342/temp/newsfeed02x.png

Site update event would have a large screenshot of index.html if updated, or another html page that is updated if the index isn't. Not sure how it would look if no html is updated.

**Comment by violasong** [comment]
Drop the js/css screenshots and code this up. Later think up a better way to indicate diff size in a visually interesting way

**Comment by kyledrake** [comment]
redesigned_newsfeed branch

**Comment by violasong** [comment]
![newsfeed02x](https://cloud.githubusercontent.com/assets/55994/8758807/a8345612-2c9d-11e5-9c9a-c01625f917aa.png)

**Comment by kyledrake** [comment]
Note to self: use "site suggestions" css for "followed 2 sites" section.
