### ISSUE TITLE
Create an information page for educators

### ISSUE THREAD

**Issue by kyledrake** [neocities/neocities#81]
So we just got the Bronx Software Academy using Neocities!

I think there should be a page for educators they can click on to get more information on how Neocities works, and how it can be used to help students learn HTML. I would also like to have educators send us an email so we can get an idea of how many teachers are using Neocities for classwork, and also get some feedback on how we can improve the service for them.

**Comment by violasong** [comment]
Yes! We should have a section on the homepage for this, and mention it in supporter plan pages. Some testimonials could be helpful.

Previously I also suggested the education page could have its own signup form for students which sends them directly to the dashboard instead of to the news feed. And maybe instead of normal topical tags, the tag field it would encourage them to tag their site with some kind of keyword for the class, like SmithNYC0814.

**Comment by kyledrake** [comment]
Okay:

There will be a /educators page or something like that describing the program, and then has a special signup.

The /education route is a "sign up" page with a link to a description of what it is so people can learn more.

We ask for username, email, password, and a single "code" that's just a tag internally.

When logged in education mode, suggested sites aren't displayed. Browse only shows tags with the same code. It is not browsable by the main platform. The site page does not exist, it only goes to dashboard.

**Comment by itsgreggreg** [comment]
Hey guys, I'm teaching coding to kids/young adults in New Orleans through a non-profit called Operation Spark (www.operationspark.org). We're currently using c9.io and gh-pages but it feels like a bit too much setup and work to me and that neocities could provide a much better, more unified experience. What I think would work well for us might be:

Set up some kind of class, kids can register through the class, once logged in they see their site files, class documents, like boiler plate or instructions, and links to the websites of other kids in the class. Still having theirsite.neocities.com would be awesome as the kids love that.

**Comment by kyledrake** [comment]
Thanks for the feedback @itsgreggreg! We will look into implementing this soon. We're moving into our office this week so we've been busy, so hopefully we'll get to this soon. I'll post updates on this ticket when I have them.

**Comment by kyledrake** [comment]
We'll need to make an announcement and have information about it linking from the front page #111

**Comment by violasong** [comment]
One thing... need to figure out what the sign up box should look like when you're signed in. Could just clean up what's already there

**Comment by kyledrake** [comment]
Quick update on this:

@violasong has finished the page for signup. It is now my job to implement it in the code, which I'm going to try to get to soon (as in, within the next few weeks).
