### ISSUE TITLE
Design HTML email template

### ISSUE THREAD

**Issue by violasong** [neocities/neocities#91]
Currently we just send plain-text emails, but it would be nice to have even just a simple header with the logo.

**Comment by kyledrake** [comment]
I can implement this quickly if you make it, so pass it back when you finish it.

I have a friend that works for an email newsletters company that can check to make sure it works on all HTML email clients too. The basic rule of thumb is to try to keep it simple and not depend on too many new HTML/CSS tricks.

**Comment by kyledrake** [comment]
Paging @kyleblakewilson

**Comment by violasong** [comment]
Cool! And yeah, I did a bunch of work on HTML emails back in 2005-7; hopefully the email client situation is less hellish now :)
